### ISSUE TITLE
[CATA] I am constantly kicked from the server by what I can only assume is the anticheat system.

### ISSUE THREAD

**Issue by zaldorn** [NRG-Wow/NRGWow-Bugtracker#1]
as the title says I am constantly being kicked and am most definitely not cheating.

the addons I am using are as follows and are all downloaded from the site that you website recommends in the how to connect area.
Bartender4
shadowed unit frames
recount
tidy plates
tiptac
weak auras
quest helper (installed but disabled due to what seems to be an addon error)

these are the only addons I have and I dont think any of them would cause me to be kicked

**Comment by Wilcalaf** [comment]
Whats your MS to the server?

**Comment by zaldorn** [comment]
100ms home and 0 ms world

**Comment by Wilcalaf** [comment]
Can you please confirm if its still happening?

**Comment by zaldorn** [comment]
It is still happening

**Comment by Wilcalaf** [comment]
Whats your in game char?

**Comment by zaldorn** [comment]
zaldorn

**Comment by Wilcalaf** [comment]
The issue of the DC should have been taken care of. check discord Notices
