### ISSUE TITLE
[CATA][QUESTS][Blasted Lands]Attune the Bloodstone

### ISSUE THREAD

**Issue by Cannonbow** [NRG-Wow/NRGWow-Bugtracker#100]
Reporter(Player/Character) Name: Cannonbow

Description:the quest is working but not perfectly you can do the quest normally but the internal and external bloodstone teleporters doesn't teleport you. 

Expected behaviour:the bloodstone teleporters should teleport you from internal to external and external to internal. 

Steps to reproduce the problem:
1.Accept the quest 
2.use the internal bloodstone teleporter that will teleport you to external
3.use the external bloodstone teleporter to teleport you back. 

This bloodstone teleporter will help you also when you go to do some quests away and you need to take back the quest completed without killing mobs to get there

**Comment by hguy23** [comment]
Thanks for report. Will be fixed on next restart.
