### ISSUE TITLE
[CATA][Spells][Death Knight] Death gate and Pestillence

### ISSUE THREAD

**Issue by djsaltynuts** [NRG-Wow/NRGWow-Bugtracker#101]
**Reporter(Player/Character) Name**: Raw

**Description**: First off the spell Death gate broke after the restart on 01/08. Appears that Pestillence is broken aswell as of that date.

**Current behaviour**: When casting Death Gate the gate itself doesn't appear after the cast is done, the spell still goes on cooldown.

As for pestillence, it doesn't spread the diseases from your current target to other targets.

**Expected behaviour**: Death gate should properly spawn the portal to Acherus. Pestillence should properly spread the diseases of your current target to the targets in close proximity.

**Steps to reproduce the problem**: Make a DK and try the spells for yourself

**Comment by NRG-Wow** [comment]
Fixed
