### ISSUE TITLE
[CATA][CLASS][HUNTER] Traps don't work

### ISSUE THREAD

**Issue by true-ede** [NRG-Wow/NRGWow-Bugtracker#103]
**Reporter(Player/Character) Name**: true-ede

**Description**: Traps don't work without Trap launcher. Yesterday they were working just fine. They trigger the cooldown and the animation is played too, but no trap spawns.

**Current behaviour**: Traps don't work

**Expected behaviour**: Traps should work without the launcher too

**Steps to reproduce the problem**:

1. Cast any Trap without Trap Launcher

**Comment by NRG-Wow** [comment]
Fixed
