### ISSUE TITLE
[CATA][GENERAL] Summonables

### ISSUE THREAD

**Issue by unexpect3d** [NRG-Wow/NRGWow-Bugtracker#104]
CATA

All summonables dont function properly: from shaman totems to cooking fires. Some of them only work while jumping. With work, i actually mean them being spawned into the world. 

Probably related to the hunter pet issue. 

Example: spell=55342 [mirror image] [mage spell] when used, nothing happens, cooldown ensues. When used while jumping, the spell functions properly. 
Example2: item=40971 [brann's communicator] used to summon an image of an NPC, doesnt work, as in, it no longer summons the NPC. Can't be used while jumping. Item used to work 2 days ago 100%. 
Example3: hunter traps (as noted in another thread) do not spawn whatsoever. 
Example4: mage portals. Can't summon mage portal :)

**Comment by virpyre** [comment]
- Teleport works but [All Portals](http://www.wowhead.com/search?q=Portal#abilities) don't after the last update.

- [Totems](http://www.wowhead.com/search?q=Totem#npc-abilities) show casting and have sounded when placed but don't show the totem, do damage or give any buffs.

- [Mirror Image](http://www.wowhead.com/spell=207169/mirror-image) doesn't show clones of character.

- [Death Gate](http://www.wowhead.com/spell=50977/death-gate) doesn't show a clickable gate.

**Comment by NRG-Wow** [comment]
Issues that came with yesterday patch are fixed
