### ISSUE TITLE
[CATA][CLASS][HUNTER] Pet stuck after dismounting in the air

### ISSUE THREAD

**Issue by true-ede** [NRG-Wow/NRGWow-Bugtracker#105]
**Reporter(Player/Character) Name**: true-ede

**Description**: Pet doesn't move after dismounting in the air. It can be moved with the "Move to" button and after that it's back to normal, but it won't attack or do anything till I did that. 

**Current behaviour**: Pet doesn't move after dismounting in the air.

**Expected behaviour**: Not the above

**Steps to reproduce the problem**:

1. Mount up on a flying mount
2. Dismount while being in the air

**Comment by Wilcalaf** [comment]
We have done a light revamp of the pet movement that has fixed this issue and it will be applied on live server soon.
Thanks for report!
