### ISSUE TITLE
[CATA][QUEST][OUTLAND] Don't Kill the Fat One

### ISSUE THREAD

**Issue by true-ede** [NRG-Wow/NRGWow-Bugtracker#106]
**Reporter(Player/Character) Name**: true-ede

**Description**: Unkor the Ruthless remains hostile and gets killed instead of turning to friendly. Can't talk with him to finish the quest.

**Current behaviour**: Unkor the Ruthless remains hostile

**Expected behaviour**: Unkor should turn friendly after losing a certain amount of health.

**Steps to reproduce the problem**:

1. Attack Unkor while doing the quest

**Comment by hguy23** [comment]
Thanks for the report. Will be fixed on next restart.
