### ISSUE TITLE
[CATA][Dungeon] Halls of Origination - Isiset falls through floor becoming untargetable

### ISSUE THREAD

**Issue by virpyre** [NRG-Wow/NRGWow-Bugtracker#107]
**Reporter(Player/Character) Name**: Various

**Description**: Isiset falls through floor becoming untargetable once she reaches 60% HP.

**Current behaviour**: Isiset falls through floor becoming untargetable once she reaches 60% HP, used .npc move to reset but it happened twice.

**Expected behaviour**: Isiset should remain stationary and not fall through the floor.

**Steps to reproduce the problem**: 
1. Get [Isiset](http://www.wowhead.com/npc=39587/isiset) to 60% HP without GM tag
2. Watch her get stuck in floor becoming untargetable
3.  Using .npc move resets her but once you get her back to 60% the concept repeats.

**Comment by NRG-Wow** [comment]
Fixed
