### ISSUE TITLE
[EN][Shaman] Enhancement Shaman Abilities

### ISSUE THREAD

**Issue by Illusie** [NRG-Wow/NRGWow-Bugtracker#110]
[//]: #  (Only reports in english will be allowed. and specific issues. everything like "ZOMG NOTHING WORKS" will be ignored / deleted)

**Reporter(Player/Character) Name**: ----

**Description**: Seems like according to Recount I took from Battleground that
there something wrong with the proc-rate of Enhancement abilities.
this specificly about Lightning shield which is maybe the most visible for the eye.

**Current behaviour**: Seems like the Lightning shield proc more often.
I took warcraftlogs as reference 
http://www.worldoflogs.com/reports/rt-n0zj91x1kg76muhq/details/7/?s=8750&e=8796

And I can clearly see the proc rate of Lightning shield is around 3%
In NRG the proc is almost double it to between 5.7%-6.5% from what I watched. (overall damage)
I must mention that the damage been checked by Recount inside Battlegrounds and not in PVE / Dummy cause (reasons)...

**Expected behaviour**: Proc rate should be lowered.

**Steps to reproduce the problem**: 

1. **Since there no Test-realm I CANNOT check it myself**
2. 
3.

I'll edit this issue later on ~ I trying to collect more info about something else.

**Comment by virpyre** [comment]
There are some things that need to be taken into account here: 
1. Does the said player have Improved Shields talent (3/3 Increase the damage of Lightning Shield by 15%)
2. Does the said player have Static Shock talent (3/3 The use of Primal Strike, Stormstrike or Lava Lash while Lightning Shield is active gives a 55% chance to deal damage equal to a Lightning Shield orb)
3. Does the said player have Glyph of Lightning Shield (Your Lightning Shield can no longer drop below 3 charges from dealing damage to attackers.)


Proc Chance = 100%
Procs When | The player takes auto attack (white) melee damage | The Player deals special (yellow) melee damage |The player takes special (yellow) melee damage

We also need a screenshot from the combat log of the BG or a video show us.

**Comment by Illusie** [comment]
I know what need take to check but I wrote in
how to reproduce on 1. there no Test realm.

all what I can do is to report and you will check (sadly) If I'm right or wrong.
The formulas are been found in Simcraft.

You can find the base % proc chance and add to it rank1/2/3 from talent.

Here is a screenshot.
https://imgur.com/a/Jcw32UU 

my estimate came from BGs a place when players are not using specific rotation to assume how much Lightning shield should proc - Which is not the 'perfect' conditions to check things.
The best way is ofc on Dummy by using Stormstrike 5000-4000 times and to see how much Lightning shield proc with each rank.

Btw the talent does not give 55% it gives 45% (rank3)
The guy from the screenshot has it rank1

About the glyph:
I think every Shaman run with that Glyph otherwise need refresh shields every like 5 second which is waste of gcds & too much effort to track. I assume that shaman has it since I didn't saw it went of from my record video files.


I checked the like ten Recounts of enhancement from different BGs.
it seems as I said on 1# message that it proc too often (look like doubling the chance it should proc.

I shared warcarft logs of shamans from BwD and you can find also logs of Enhancements from FL and DS.
You can find and compare from different logs that the Proc chance of Lightning shield is around of 2% up to 4% of total damage that Enh does.


Edit:

> Procs When | The player takes auto attack (white) melee damage | The Player deals special (yellow) melee damage |The player takes special (yellow) melee damage


the answer is here http://cata-shoot.tauri.hu/?spell=51527

**Comment by Illusie** [comment]
https://imgur.com/a/k3vEBJ5 - a Enhancement shaman from DS / Madness boss (another pserver)
this is his overall Lightning shield. (12min fight boss)

and here blow is Enh from different mob/bosses pulls in NRG

https://imgur.com/a/LZWVnUa - lightning shield 11.1% overall damage. (66 procs!).
https://imgur.com/a/XbB5sEo - here is from Boss fight when Flametongue is 2nd overall damage.
Lightning shield 6.3% overall damage.
https://imgur.com/a/tRkHuQa - another example.

worldoflogs from Retail if you want to compare = http://www.worldoflogs.com/ranking/eu-us/blackwing-descent/chimaeron/normal-10/dps/shaman/enhancement/

I tried look for Enhancement with T11 gear I couldn't ;(

Flametongue Weapon
1. Each hit has a $33757h% chance of triggering three extra attacks with $s2 bonus attack power
2. Increasing magical damage done by $10400s2%$?s55451[ and increasing spell critical strike chance by $55451s1%.][.] Each hit causes $/77;s2 to $/25;s2 additional Fire damage

Windfury Weapon
1. Each hit has a $33757h% chance of triggering three extra attacks with $s2 bonus attack power
2. Unleashing this enchantment deals $73681s3% of weapon damage

Lightning shield
GCD: 1.5 seconds
Coefficient: 0.267
Trigger Spell: 26364

melee or ranged attack hits the caster, the attacker will be struck for $26364s1 Nature damage

Variables    : $mult1=$?s16261[${1.05}][${1.00}]
$mult2=$?s16290[${1.10}][${$<mult1>}]
$bonus=$?s51881[${1.15}][${$<mult2>}]

Taken from Simcraft 4.3.4
need also calculate Mastery %
I hope it's help.

**Comment by Crushhymn** [comment]
Flametongue is currently doing a ton of damage, though 30% resi reduction and 18% from talents, it's common getting hit for almost 2k per hit. 
https://youtu.be/sD9anO-GViY?t=104
While i can't say how his overall gear is, he does have 2 x No'kaled from DS, even in RF mode this is a 390 weapon. This would probably mean that his gear is in the range of ilevel 380-410.
He is hitting the target dummy (0% resilience) for less than 3k, spiking at 5k during burst and cooldowns.
The shaman in the video linked would do a little less than 2k using the 30% and 18% i mentioned, but we're talking an endgame geared shaman from Al'Akir EU on retail, we're currently capped at ilevel 359 weapons from Arena.

Will look into Lightning shield later, as i currently do not have a lot of information myself, however, just hitting a shaman with LS is a dangerous act without self healing.

**Comment by Wilcalaf** [comment]
After checking the issue for a while and speaking with @Illusie 
It seems the proc chance he was talking about is regarding Static shock and not Lightning shield.
Lightining shield as a proc chance of 100% and 1.5 cooldown which is working properly after tests.

https://media.discordapp.net/attachments/468525884127576085/478205061898698757/unknown.png
https://media.discordapp.net/attachments/468525884127576085/478205175916527617/unknown.png
https://media.discordapp.net/attachments/468525884127576085/478205386722246674/unknown.png

And test with multiple targets hitting the shaman, the proc rate increased because it was split between targets

https://media.discordapp.net/attachments/468525884127576085/478206865269063700/unknown.png
https://media.discordapp.net/attachments/468525884127576085/478207041656324107/unknown.png

Lightning shield is working properly.
