### ISSUE TITLE
[OUTLAND][NPCs] Neltharaku Flight Issues

### ISSUE THREAD

**Issue by virpyre** [NRG-Wow/NRGWow-Bugtracker#111]
**Reporter Name**: Various Players

**Description**: Neltharaku won't stop flying when you click on him.

**Current behaviour**: You click on Neltharaku and he just keeps flying around in his patrol pattern.

**Expected behaviour**: When you click on Neltharaku he should stop flying and face until you take your mouse off of him then he'll resume flying again.

**Steps to reproduce the problem**:
1.  Take the quest by using _.quest add10811_
2.  Try chasing him around a few times to talk to him have heard using click to move works well.
3. The only way to keep him stationary right now is his have gm us _.npc follow_ and stay there forever.

**Comment by NRG-Wow** [comment]
This has been fixed and will be applied on next patch.
Thanks for report!
