### ISSUE TITLE
[CATA][Spells][Classes] Seal of Righteousness triggers in melee range, not from abilities that should apply a seal, regardless of range to the target

### ISSUE THREAD

**Issue by Gubbyfishy** [NRG-Wow/NRGWow-Bugtracker#112]
**Reporter(Player/Character) Name**: Hundoslavus

**Description**: Seal of Righteousness does not trigger from associated Paladin spells that should apply it unless you are standing closer than melee range compensation.

**Current behaviour**: Example of Judgement: Casting Judgement within 1-2 yards of the target properly applies one instance of Seal of Righteousness. Casting Judgement further away applies no seal damage at all. The same goes for Crusader Strike, Divine Storm and Hammer of Wrath.

EDIT: Having your back turned against a target (which can be the scenario of Divine Storm or Judgement) does not apply SoR damage either, but it does in 1-2 yards if you are facing them.

**Expected behaviour**: The expected behavior is that once a target is hit by any of the above mentioned abilities, one instance of Seal of Righteousness should also apply on top. Not applying seal damage to all targets it when using Divine Storm because they are fanned out is infuriating and brings Paladin AoE dps below average and requires more positioning effort than intended.

**Steps to reproduce the problem**:

1. Cast either Judgement, Crusader Strike, Divine Storm or Hammer of Wrath on a target with Seal of Righteousness active while more than ~1-4 yards away. Does it apply the Seal damage? No.
2. Stand in a target's face. Use above mentioned abilities again. Does the Seal apply from those abilities? Yes it does.
EDIT: 3. Stay in movement. Use crusader strike on a mob chasing you. Does it apply Seal damage?

**Comment by NRG-Wow** [comment]
I just quick tested this and i was not able to reproduce your issue

![image](https://user-images.githubusercontent.com/41172388/43582597-a4d4c5c6-9665-11e8-9ec5-e4e70664a585.png)

![image](https://user-images.githubusercontent.com/41172388/43582663-d49f2df0-9665-11e8-8196-ed02e8c34e06.png)

We gonna need more info because the reproduction steps provided are not enough to reproduce the problem

**Comment by Gubbyfishy** [comment]
![sealofrighteousness](https://user-images.githubusercontent.com/6233159/43646311-e0085110-9734-11e8-9249-b4eb3a0ebf65.PNG)
I don't know what you are doing differently than I am but I literally have my back turned against a mob and a 4~5 yard Judgement didn't apply the Seal. It does if I stand within ~1-2 yds.

EDIT: Hammer of Wrath for comparison
![hammerofwrath](https://user-images.githubusercontent.com/6233159/43646835-44ec2484-9736-11e8-87ca-fab1f017f3ca.PNG)
![hammerofwrath2](https://user-images.githubusercontent.com/6233159/43646847-4ab6e444-9736-11e8-9525-386f53712275.PNG)

![divinestorm](https://user-images.githubusercontent.com/6233159/43646611-a84d30f0-9735-11e8-9c34-6257953ffd13.PNG)
![divinestorm2](https://user-images.githubusercontent.com/6233159/43646620-ad059a6a-9735-11e8-993d-6661065e26f3.PNG)

Divine Storm as an example. Funny observation is that if you have your back turned against a target, it doesn't apply SoR either.

Updating my OP with more details.

**Comment by Gubbyfishy** [comment]
![divinestorm](https://user-images.githubusercontent.com/6233159/43646611-a84d30f0-9735-11e8-9c34-6257953ffd13.PNG)
![divinestorm2](https://user-images.githubusercontent.com/6233159/43646620-ad059a6a-9735-11e8-993d-6661065e26f3.PNG)

Divine Storm as an example. Funny observation is that if you have your back turned against a target, it doesn't apply SoR either.

**Comment by Wilcalaf** [comment]
Im going to clone your char and test with it.

**Comment by Wilcalaf** [comment]
I have cloned your char and reproduced the issue, it looks like a talent is causing it. we are researching.
-- Edit
Seals of commands on retri tree is causing it. Need to research if its blizzlike or not.

**Comment by Wilcalaf** [comment]
Its blizzlike. the Talent Seals of command turns Seal of Righteousness to hit targets in meele range which means its a cleave. wont work on target from behind you and only on meele range
![image](https://user-images.githubusercontent.com/9047365/43671575-544eb846-97a5-11e8-872f-bfd1214dde6c.png)
