### ISSUE TITLE
[CATA][RAID] Throne of the Four Winds - Al'Akir

### ISSUE THREAD

**Issue by virpyre** [NRG-Wow/NRGWow-Bugtracker#114]
**Reporter**: Alpha and Omega's Guild

**Description**: [Al'Akir](http://www.wowhead.com/npc=46753/alakir) once defeated currently doesn't spawn Heart of Wind.

**Current behaviour**: Currently Heart of Wind spawns out on an invisible platform with no way for players to get to it.

**Expected behaviour**: Once defeated Al'Akir should spawn Heart of Wind on death next to copse.

**Steps to reproduce the problem**:
1. Goto Throne of the Four Winds
2. Kill Al'Akir
3. Look for the invisible platform.

[Throne of the Four Winds](http://www.wowhead.com/throne-of-the-four-winds)
[Heart of Wind: 10-Man](http://www.wowhead.com/object=207891/heart-of-wind)
[Heart of Wind: 25-Man](http://www.wowhead.com/object=207894/heart-of-wind)
[Heart of Wind: H25-Man](http://www.wowhead.com/object=207892/heart-of-wind)

**Comment by NRG-Wow** [comment]
Did you actually see it spawn on an invisible platform?
i dont see it spawn at all, do you have SS?

**Comment by MoireMoire** [comment]
It spawns, there is no platform because Al'akir destroys it during phase three. What is missing is the buff that makes people fly within the zone.

**Comment by NRG-Wow** [comment]
Players will get the fly buff now after Alakir is defeated
it will be on live server after next patch.
Thanks for report
