### ISSUE TITLE
[CATA][Quests][Mount Hyjal] Return to Alysra

### ISSUE THREAD

**Issue by piccolobsc** [NRG-Wow/NRGWow-Bugtracker#115]
**Reporter(Player/Character) Name**:  Piccoshaman

**Description**:  Alysra is not there to turn the quest in

**Current behaviour**: NPC to turn the quest in is not there

**Expected behaviour**: Spawn the NPC

**Comment by hguy23** [comment]
Thanks for report. Will be fixed on next restart.
