### ISSUE TITLE
[CATA][Quests][Netherstorm] Flora Of The Eco domes

### ISSUE THREAD

**Issue by Cannonbow** [NRG-Wow/NRGWow-Bugtracker#116]
Reporter(Player/Character) Name: Cannonbow

Description: when I accept the quest I need to use the item energy field modulator on farahlon lasher to make him réd (enemy) but it doesn't work it still yellow

Current behaviour: farahlon lasher still yellow and it says there is no target

Expected behaviour: click on the energy field modulator to change yellow to red enemy and take aggro. 

Steps to reproduce:
1.accept the quest 
2.go to farahlon lasher 
3.click on item energy field modulator to change him to enemy and to kill him 
4.finish the quest.

**Comment by hguy23** [comment]
Will be fixed on next restart.
