### ISSUE TITLE
[Cata][Classes]Pets

### ISSUE THREAD

**Issue by unexpect3d** [NRG-Wow/NRGWow-Bugtracker#121]
As you probably are already aware there are a few classes that greatly benefit from their pets in this expansion and throughout wow history in general, they provide an interesting funtionability in the game.
As you are probably NOT aware the status of these so called pets on this server ranges from poor to "fucking kidding me?".

Main issues:

1. Hunter pets randomly disappear and get ABANDONED, as in lost forever and unrecoverable. 
2. All pets (from all classes) suffer from pathing problems, as in, they get stuck on ledges in battlegrounds and such. Easiest solution would be to have them summoned automatically to the players position when reached X distance from him (X being either/both the distance it usually gets dismissed or when it no longer has any paths available for them to walk on like for example: when jumping from platform to platform in Throne of the Four Winds [zone=5638], or by using the Slipstreams [npc=47066]; teleport should be happening when the player reaches solid ground).

**Comment by Wilcalaf** [comment]
Hello, we already have a rewrite for Pet pathfinding which  will hopefully solve also the pet disappearing issue. its on testing atm and will be released soon.

**Comment by Illusie** [comment]
The pets should not recieve auto summon if they are far distance from their Owner.
you should click to summon then and waste gcd for it.

The pets should disappear if they far from their Owner it's known problem when someone send his Pet from end of BG map to attack you and it doesn't disappear.

In Raids situation like Tot4w if you send your pet on target and you jump to other platform
he should disappear from distance.
~that why you need make him /follow and when you jump between platforms the Pet should jump/follow you at same speed as you.~
But again IF you send the pet on target and forget to press /follow he will disappear from distance.

proof: 
https://www.youtube.com/watch?v=rJ1sznv51vs
0:40-1:00
hunter has pet > hunter hasn't pet.
also
5:20
https://www.youtube.com/watch?v=nVKN-nKhXxg
1:12

**Comment by Wilcalaf** [comment]
Please let us  know if it still happening after todays patch

**Comment by hguy23** [comment]
@unexpect3d
