### ISSUE TITLE
[CATA][Quests][Shadowmoon Valley] Neltharaku's Tale

### ISSUE THREAD

**Issue by djsaltynuts** [NRG-Wow/NRGWow-Bugtracker#123]
**Reporter(Player/Character) Name**: Raw

**Description**: You're supposed to go through some RP story with Neltharaku

**Current behaviour**: You go through all the gossip options but quest doesn't complete afterwards.

**Expected behaviour**: After going through the story the quest should complete

**Steps to reproduce the problem**: Get the quest "Neltharaku's Tale" (ID: 10814) and try it out.

**Comment by hguy23** [comment]
Will be fixed on next restart. Completly with new pathing and gossip.
