### ISSUE TITLE
[CATA][Reputation][Darnassus] Riding trainer Jartsam

### ISSUE THREAD

**Issue by Icundia** [NRG-Wow/NRGWow-Bugtracker#127]
[//]: #  (Only reports in english will be allowed. and specific issues. everything like "ZOMG NOTHING WORKS" will be ignored / deleted)

[//]: # (Please write the titles of the issues following the format:)
[//]: # ([CATA][Quests][Zones] Quest name)
[//]: # ([WOTLK][Spells][Classes] Spell name)
[//]: # ([WOTLK][Talents][Classes] Talent name)
[//]: # ([CATA][Glyphs][Classes] Glyph name)
[//]: # ([CATA][NPCs] NPC name)

**Reporter(Player/Character) Name**: Icundia (Worgen)

**Description**: Not able to buy riding skill from Jartsam in Darnassus even with exalted status as non- night elf.

**Current behaviour**: Jartsam says that you need to be exalted with Darnassus to be able to buy riding skill from him.

**Expected behaviour**: Should be able to buy riding skill once level 20 and exalted status with Darnassus.

**Steps to reproduce the problem**:

1. Level to 20
2. Gain exalted status with a non-night elf with Darnassus
3. Talk to Jartsam

**Comment by Wilcalaf** [comment]
Will be fixed on next restart
