### ISSUE TITLE
[//]: # ([CATA][Guild Achievement Bug] 

### ISSUE THREAD

**Issue by priide** [NRG-Wow/NRGWow-Bugtracker#128]
**Reporter(Player/Character) Name**: Pride

**Description**: Describe the problem: last week when we killed al'akir on tot4w we didnt get al'akir guild achive we were 10 man from guild idk why we didnt get it
also today we cleared tot4w as 10 m from guild & we didnt get achive . somehow we gets the heroic achive instead if nm one in guild but for player achivement we get nm version the probleme is only on guild achives . also when we killed chemaeron as 10 m from guilde we didnt get the achive .

Screenshots : https://imgur.com/a/LmTf2kX  -----   https://imgur.com/a/fFdBm8T
**Current behaviour**:  ^ 
**Expected behaviour**: we get nm version on guild achivement so we get our tot4w guild ach

**Steps to reproduce the problem**:

1. no idea
2. 
3.

**Comment by Wilcalaf** [comment]
Needs research

**Comment by Wilcalaf** [comment]
We have a potential fix that will be applied on next restart, however need Players confirmation
@priide 
So please let us know next time you go there (and after we applied the patch) if you still cant get the credit for it

**Comment by priide** [comment]
Alright just waiting for the raids reset so we can do it again thx for the help

**Comment by Wilcalaf** [comment]
I was told that Alakir was given correctly today
Need confirmation on Chimaeron and Nefarian

**Comment by MoireMoire** [comment]
We got chimaeron the last week, on the second kill.

**Comment by priide** [comment]
Chemareon worked on 2nd kill also tot4w achive working correctly now Thx !

**Comment by Wilcalaf** [comment]
Awesome!
