### ISSUE TITLE
[CATA][Profession][Archeology] No skill gain

### ISSUE THREAD

**Issue by Boome01** [NRG-Wow/NRGWow-Bugtracker#13]
[//]: #  (Only reports in english will be allowed. and specific issues. everything like "ZOMG NOTHING WORKS" will be ignored / deleted)

[//]: # (Please write the titles of the issues following the format:)
[//]: # ([CATA][Quests][Zones] Quest name)
[//]: # ([WOTLK][Spells][Classes] Spell name)
[//]: # ([WOTLK][Talents][Classes] Talent name)
[//]: # ([CATA][Glyphs][Classes] Glyph name)
[//]: # ([CATA][NPCs] NPC name)

**Reporter(Player/Character) Name**: Boome

**Description**: After digging a archeology site or solving player should gain experience depending on his level.

**Current behaviour**: Player doesn't get any experience after digging or solving at all.

**Expected behaviour**: After digging a site (after every succesfull dig) or solving player should get certain amount of experience depending on his level.

**Steps to reproduce the problem**:

1.  Fix experience gain after digging.
2.  Fix experience gain after solving.
3.

**Comment by Wilcalaf** [comment]
Its fixed on PTR and will be on production after next patch is applied.
