### ISSUE TITLE
Darkmoon Card: Hurricane is not working

### ISSUE THREAD

**Issue by Artmystile** [NRG-Wow/NRGWow-Bugtracker#130]
Dear sr.

My character name is Manias

The trinket Darkmoon Card: Hurricane not working currently

doesn't proc the nature damage with ranged attacks

**Steps to reproduce the problem**:

1. DPS anything
2. See that the trink is not procing
3.cry because time i spent farming it

Thanks i hope this helps fixing

**Comment by Wilcalaf** [comment]
Its working.
Proc rate is around 3% for actual hit for hunters (even less sometimes)
![image](https://user-images.githubusercontent.com/9047365/43724800-93ac1b6e-99a3-11e8-98b5-f5b7c166dc5e.png)
