### ISSUE TITLE
[Cata][Profession][Alchemy] Transmute: Living Elements

### ISSUE THREAD

**Issue by Pulse159** [NRG-Wow/NRGWow-Bugtracker#133]
**Reporter(Player/Character) Name**: Bri

**Description**: The Transmute: Living Elements skill does not produce between 14 and 16 random Volatile Elements chosen between air, water, earth, or fire. It instead creates the "Random Volatile Element" Item that is used for the tooltip for the crafting recipe.

**Current behaviour**: Generates a useless dummy item instead of the random Volatile Elements that it should.

**Expected behaviour**: The Transmute should give you between 14 and 16 (At my current Alchemy level of 525) chosen randomly between the above listed Volatile Elements.

**Steps to reproduce the problem**:

1.  Use the recipe "Transmute: Living Elements".
2.  End up with useless items.
3. Have way too many Volatile Life and not enough of anything else.

**Comment by MoireMoire** [comment]
It gives you both the random volatile element and fire/earth/water/air volatiles.

**Comment by Pulse159** [comment]
You're correct, however after the last 5 transmutes all I have ever gotten is Volatile Water. Either the random generation is broken or I have very bad luck. Will put in another bug report if its all water after a week.

**Comment by Pulse159** [comment]
Just got Volatile Earth. Seems everything is good ^.^
