### ISSUE TITLE
[CATA][Spells][Paladin] Guardian of Ancient Kings (Retribution)

### ISSUE THREAD

**Issue by Gubbyfishy** [NRG-Wow/NRGWow-Bugtracker#136]
**Reporter(Player/Character) Name**: Hundoslavus

**Description**: Guardian of Ancient Kings (Retribution) will attack its owner if idle and if owner heals him/herself

**Current behaviour**: Cast Holy Light, Flash of Light or Divine Light on yourself. If the Guardian summon is idle, it will start attacking you until it acknowledges a new target. Only above abilities have been tested personally.

**Expected behaviour**: The Guardian should either remain idle by the master's side or continue to pursue the owner's most recently attacked target.

**Steps to reproduce the problem**:

1. Cast GoaK as Retribution
2.  Cast any healing spell on yourself
3. The Guardian should begin attacking you. (This actually does no damage, but still causes pushback and damage is actually combat logged.)

**Comment by Wilcalaf** [comment]
Fixed locally and will be pushed on next patch.
thanks for report
