### ISSUE TITLE
[CATA][Spells][Druid]Skull Bash(Guardian)

### ISSUE THREAD

**Issue by Babunibre** [NRG-Wow/NRGWow-Bugtracker#140]
Reporter(Character) Name: Paxler
1./2. What is the problem:
 When i use Skull Bash on the target it works halfway. Good part is: it does interrupt the target(the interruptable targets are getting it), but the bad one is the spell says "You charge and skull bash the target..." the "charge" part is not working basically you are just staying in the same play not moving while the target is interrupted.

3.Expected behaviour:
When you use skull bash: 1. You should first charge to the target than interrupt it (happens pretty fast, but it should follow this sequence). because if you get somehow rooted/immobilized in that particular part the interrupt fails.
2. Even if the target is not casting any spell, just standing there, you should be able to use Skull Bash on target just for the purpose of getting closer to it/faster.Basically you get mini Charge to target within 13 yards. 

Steps to reproduce the problem:
1. Go to nearby dummy.
2. Use spell Skull bash on it
3.You will see yourself being rooted in the same place.

**Comment by Wilcalaf** [comment]
Hi im testing it, it seem to be like a Range issue, looks like theres a certain distance that if you use it it wont charge but it will still interrupt.

still investigatin

**Comment by Wilcalaf** [comment]
Thanks issue, spotted and fixed locally. fix will be applied on next patch.
please reopen if you still having issues after next patch
