### ISSUE TITLE
([CATA][Quests]Hyjal] Emerald Allies

### ISSUE THREAD

**Issue by Supernachos12** [NRG-Wow/NRGWow-Bugtracker#141]
**Reporter(Player/Character) Name**: Nacho

**Description**: Npc i'm supposed to talk to is not here. Making it impossible to quest in Hyjal since it's one of the first quests in the area.

**Current behaviour**:  Npc isn't here. 

**Expected behaviour**: Alysra should be in the Ruins of Lar'donir and open new quests in Hyjal.

**Steps to reproduce the problem**:

1. Get "Emerald Allies"
2. Go on the "?" in the Ruins of Lar'donir.

Quest worked fine for my 2 first toons. So i guess something broke it recently.

**Comment by Wilcalaf** [comment]
The npc phasing was corrected
