### ISSUE TITLE
[CATA][Quests][The Lost Isles] Miner Trouble NPC speaks in Spanish

### ISSUE THREAD

**Issue by virpyre** [NRG-Wow/NRGWow-Bugtracker#142]
**Reporter Name**: Higglespark

**Description**: The quest [Miner Troubles](http://www.wowhead.com/quest=24858/bilgewater-cartel-represent) in the servers needs to be translated seems like it's in Spanish.

**Current behaviour**:  NPC talks in Spanish.

**Expected behaviour**: English should default unless stated otherwise.

**Steps to reproduce the problem**:
1.  Accept quest 14021
2.  Follow the NPC
3. List to her talk

**Comment by Wilcalaf** [comment]
It has been fixed locally and it will be applied on next server patch.
thanks for report
