### ISSUE TITLE
[CATA][Quests][The Lost Isles] Capturing the Unknown Unable to Continue Quest Chain in Current State

### ISSUE THREAD

**Issue by virpyre** [NRG-Wow/NRGWow-Bugtracker#143]
**Reporter Name**: Higglespark

**Description**: The quest [Capturing the Unknown](http://www.wowhead.com/quest=14031/capturing-the-unknown) is an instant complete quest a player isn't going to know to recheck the cave to get [Orcs Can Write?](http://www.wowhead.com/quest=14233/orcs-can-write) if the said player misses this quest they will be unable to begin the next chain quest.

**Current behaviour**: [Capturing the Unknown](http://www.wowhead.com/quest=14031/capturing-the-unknown) is an instant complete quest.

**Expected behaviour**: [Orcs Can Write?](http://www.wowhead.com/quest=14233/orcs-can-write) should be given during [Miner Troubles](http://www.wowhead.com/quest=14021/miner-troubles) to avoid any confusion.

**Steps to reproduce the problem**:
1.  Accept quest 14031
2.  Turn in quest 14031
3. No other NPC's to talk to unless you go in the cave to get quest 14233

**Comment by Wilcalaf** [comment]
Mechanics of the Capturing the unknown quest are working. theres no reason to have this on instant complete.

The quest "auto completion" has been canceled and players will have to go to check the cave now.

**players who already got this quest on another char will have to clear cache to see it properly**

It will take effect after next restart
