### ISSUE TITLE
[CATA][Quests][The Lost Isles] A Goblin in Shark's Clothing - The Hammer destroys Mechashark X-Steam sub

### ISSUE THREAD

**Issue by virpyre** [NRG-Wow/NRGWow-Bugtracker#144]
**Reporter Name**: Higglespark

**Description**: The quest [A Goblin in Shark's Clothing](http://www.wowhead.com/quest=24817/a-goblin-in-sharks-clothing) is hard to complete without the use of [Mechashark X-Steam](http://www.wowhead.com/npc=38318/mechashark-x-steam) it gets destroyed to fast by [The Hammer](http://www.wowhead.com/npc=36682/the-hammer) you have a chance to use 2 abilities before the Mechashark X-Steam disappears and you get ejected.

**Current behaviour**: [Mechashark X-Steam](http://www.wowhead.com/npc=38318/mechashark-x-steam) it gets destroyed to fast by [The Hammer](http://www.wowhead.com/npc=36682/the-hammer)

**Expected behaviour**: https://www.youtube.com/watch?v=-u6f3CKkveo

**Steps to reproduce the problem**:
1. Accept quest 24817
2. Touch the Mechashark X-Steam Pillar
3. Try to fight The Hammer

**Comment by Wilcalaf** [comment]
HP of the Mechashark has been increased a little bit so its doable.
Will be taking effect from next restart
