### ISSUE TITLE
[CATA][Lockboxes] Elementium lockboxes give no gold

### ISSUE THREAD

**Issue by MoireMoire** [NRG-Wow/NRGWow-Bugtracker#148]
**Reporter(Player/Character) Name**: Moire

**Description**: No gold inside it, only one green and sometimes another lockbox

**Expected behaviour**: around 30g, a green item and sometimes another lockbox
**Steps to reproduce the problem**:

1. Get an elementium lockbox
2. Open it
Opened about 60 of them and none gave golds

**Comment by virpyre** [comment]
They should contain 25-35 gold (with boost rates it should be 75-105 gold) and an ilevel 300-312 uncommon item. There is a small chance that the uncommon item will be another Elementium Lockbox, containing 2x more gold and another item (which can also be another lockbox... each time you loot an additional lockbox the gold amount increases by x2 of the previous amount).

**Comment by hguy23** [comment]
Will be fixed on next restart :1st_place_medal:
