### ISSUE TITLE
[CATA][Spells][Druid] Flight Form

### ISSUE THREAD

**Issue by Supernachos12** [NRG-Wow/NRGWow-Bugtracker#155]
**Reporter(Player/Character) Name**: Nacho

**Description**: While flying, you can't shift out and shift back to the fight form without falling to the ground

**Current behaviour**: When you shift out in the air, and shift back to the flight form, your character falls to the ground. 

**Expected behaviour**: You should be able to use your flight form while falling if your out of combat.

**Steps to reproduce the problem**:

1. Fly in flight form
2. Shift out while in the air
3. Use the flight form again while falling

**Comment by Pulse159** [comment]
I can verify this bug, it can be quite annoying but at least you don't take fall damage when you hit the ground.

**Comment by MoireMoire** [comment]
Unless you get out of a dungeon and fall for 100+ yards killing yourself. That's udderly annoying

**Comment by hguy23** [comment]
Will be fixed on next restart. Thanks for report.
