### ISSUE TITLE
[EN][Profession] Archeology

### ISSUE THREAD

**Issue by Illusie** [NRG-Wow/NRGWow-Bugtracker#159]
[//]: #  (Only reports in english will be allowed. and specific issues. everything like "ZOMG NOTHING WORKS" will be ignored / deleted)

**Reporter(Player/Character) Name**: ----

**Description**: Archeology Digsites not appear on map.

**Current behaviour**: I learnt Archeology and I don't have digsites
Track on Digsites is flagged V (on)

On my other alt I have opposite thing
I reached 525 archeology and now I can't remove the Track Digsites.

**Expected behaviour**: Track Digsites should work like Track Minerals or Herbs
If you V it then you see on map
if you don't you are not suppost to see it map

**Steps to reproduce the problem**:

1. I deleted cache
2. I also removed all addons

still not working.

**Comment by Wilcalaf** [comment]
You are currently on the maximum fragments that you can hold.
Solve some nightelf puzzles and you will start seeing them.
