### ISSUE TITLE
[EN][Shaman] Magma Totem

### ISSUE THREAD

**Issue by Illusie** [NRG-Wow/NRGWow-Bugtracker#168]
[//]: #  (Only reports in english will be allowed. and specific issues. everything like "ZOMG NOTHING WORKS" will be ignored / deleted)

**Reporter(Player/Character) Name**: ----

**Description**: Magma totem ~~range~~ radius

**Current behaviour**: I am not sure but I think magma totem range is bit bigger than it should.
I would like if you test it out.

**Expected behaviour**:  magma totem should has smaller ~~range~~ radius.
according to spell description 8 yard radius

It also missing the animation according to what I saw (cant be sure I dont have shaman to check myself)

**Steps to reproduce the problem**:

1.  drop magma totem, be stealth player and try to see ~~yards~~ radius

**Comment by virpyre** [comment]
![2018-08-15](https://user-images.githubusercontent.com/41524551/44172699-f41a0d80-a0ab-11e8-8406-f861b8a2dec1.png) no damage range

![2018-08-15 1](https://user-images.githubusercontent.com/41524551/44173348-9edefb80-a0ad-11e8-87f5-b96b0f797ef6.png) damage range

You might be thinking of Fire Nova it has a 10-yard range, and is cast when Fire Shock is present.

**Comment by Illusie** [comment]
Nope I clearly speak about Magma totem.
Fire nova is ability that enh shaman need flame shock first to use.
Improved lava lash spread if up to 4 targets in 12 yard than you fire nova to aoe and do big damage.
Ele can use it too but it less familiar cause Chains > Fire Nova.

That not what im talking about ^

I'm talking about Magma totem it does damage to all (aoe) damage every 2 sec with a range/radius of 8yard to each direction.
If the totem is already has 8yard radius so all fine and it's just my mistake all I wanted is to be sure.

Because as explained above - in one of many battleground I did today. me and my rogue from my BG team just got out of stealth (I used Invisible as mage)
by the magma totem and we walked nearby it and we pretty sure we was in larger range and it got hit by the totem.

That all what I report about.

**Comment by virpyre** [comment]
Okay so you used Invisible as a mage and your friend just broke Stealth and the totem hit you from a much larger radius than 8 yards.

needs more investigation or a reference.

**Comment by Wilcalaf** [comment]
I tried to reproduce the issue quickly with a dummy and i dont seem to be able to.
ill try later with 2 player targets.

**Comment by Illusie** [comment]
reference to what
just drop the magma totem and check the radius, It should be 8yard to any direction.
and magma totem can hit multi-target (aoe)

as I said if the totem has 8 yard radius than all fine. It was battleground and I don't have shaman to check myself. if not then fix it.

And there is also animation to that totem. I'm not sure the animation was in Cata or other expansion.

here:
https://images.duckduckgo.com/iu/?u=http%3A%2F%2Fmedia-azeroth.cursecdn.com%2Fattachments%2F71%2F356%2F635518313390133809.png&f=1

https://wow.zamimg.com/uploads/screenshots/normal/366242-magma-totem.jpg


If it's not cata the magma totem should has this animation or not
but if not i'm pretty sure it has any kind of animation.

~

**Comment by Wilcalaf** [comment]
![image](https://user-images.githubusercontent.com/9047365/44238899-50218680-a1bf-11e8-9ea4-caae773b8eb3.png)

![image](https://user-images.githubusercontent.com/9047365/44238933-6fb8af00-a1bf-11e8-913f-57c85ff21d62.png)

![image](https://user-images.githubusercontent.com/9047365/44239009-d1791900-a1bf-11e8-91e2-056fda75f7f4.png)


![image](https://user-images.githubusercontent.com/9047365/44238952-80692500-a1bf-11e8-8b34-f3e4ca14c090.png)

The range of the totem is working as intended from those checks.
Im standing at 10 yards exactly. it only works from around 2 yards closer
