### ISSUE TITLE
[WOTLK][Quests][Basin Sholazar] The Lost Mist Whisper treasure 

### ISSUE THREAD

**Issue by Cannonbow** [NRG-Wow/NRGWow-Bugtracker#175]
Reporter Name:Cannonbow

Description:Well I can't hit the warlod tarte it's saying interrupted so I can't attack that target.

Expected behaviour: I should hit the warlord tartek to kill him and finish the quest and to continue.

Steps:
1.accept the quest 
2.you get the item and you kill the warlord 
3.you finish the quest and take reward

**Comment by hguy23** [comment]
Would be fixed on next update.
