### ISSUE TITLE
[CATA] Client not starting.

### ISSUE THREAD

**Issue by ghost** [NRG-Wow/NRGWow-Bugtracker#18]
Set the realmlist, deleted Cache, Ran as administrator, changed compatibility mode, added to DEP exceptions.
Nothing. 
When I'm trying to launch the game, it stays idle for a couple of minutes, then, [THIS](https://i.imgur.com/gi6zL36.png) appears

**Comment by Boome01** [comment]
Make sure to follow this:

1) Go to your World of Warcraft folder
2) Right click on your Data folder
3) Open properties
4) Unmark "read only"
5) Go to your realmlist
6) Right click on your realmlist
7) Open properties
8) Unmark "read only"

**Comment by ghost** [comment]
Still not working.
Now it's showing [this](https://i.imgur.com/pSsKaJZ.png)

**Comment by Wilcalaf** [comment]
Try to Rename also WowCircle.exe to Wow.exe

**Comment by Illusie** [comment]
client not working is not bug report. please =.="

**Comment by Wilcalaf** [comment]
@Illusie is right
@Nescu Please request support on discord channel for kind of issues like this.
