### ISSUE TITLE
Utgarde Pinnacle

### ISSUE THREAD

**Issue by Diddled** [NRG-Wow/NRGWow-Bugtracker#184]
Zone: Utgarde Pinnacle Heroic (possibly normal too)

Reported by Lumpyspace

Description: Second boss never spawns last add. Third boss event never starts

Current behavior: Gortok Palehoof event summons first three adds, fourth one never spawns. Skadi the Ruthless flies off then his photo drake respawns and the boss fight even never starts.
Expected behaviour: Gortok should spawn each add one at a time after activating the orb in his room then activate himself for kill. Skadi should fly off spawning harpoon adds and periodically be able to be shot with harpoons and fly over freezing the ground
Steps to reproduce the problem:

Gortok:
click orb in his room
kill first three adds as they spawn
fourth add never spawns

Skadi:
run up to him
he flies away, drake respawns and nothing happens

**Comment by Wilcalaf** [comment]
Im pretty sure last time i tested , Skadi the ruthless was working properly. need to recheck.

**Comment by Wilcalaf** [comment]
Both issues will be fixed on next Patch.
