### ISSUE TITLE
Eye of Eternity phase 3

### ISSUE THREAD

**Issue by Diddled** [NRG-Wow/NRGWow-Bugtracker#189]
Zone: The Eye of Eternity
Reported by Lumpyspace

Description: boss evades endlessly can't be killled
Current behavior: Phase one works as intended as does phase 2, when phase three starts the party mounts drakes then the platform respawns with boss inside it and he evades all attacks
Expected behaviour:phase three platform breaks, players mount drakes, kill boss with drakes

Steps to reproduce the problem:

get Mal to phase three and mount drakes

**Comment by Wilcalaf** [comment]
A hotfix for this will be implemented on next patch

**Comment by Wilcalaf** [comment]
Reset will stop after todays patch
