### ISSUE TITLE
[CATA][Dungeon][Npc] In Uldaman final boss repeatable 

### ISSUE THREAD

**Issue by TeenWolf2** [NRG-Wow/NRGWow-Bugtracker#19]
[//]: #  (Only reports in english will be allowed. and specific issues. everything like "ZOMG NOTHING WORKS" will be ignored / deleted)

[//]: # (Please write the titles of the issues following the format:)
[//]: # ([CATA][Quests][Zones] Quest name)
[//]: # ([WOTLK][Spells][Classes] Spell name)
[//]: # ([WOTLK][Talents][Classes] Talent name)
[//]: # ([CATA][Glyphs][Classes] Glyph name)
[//]: # ([CATA][NPCs] NPC name)

**Reporter(Player/Character) Name**: Zoom

**Description**: Final boss in Uldaman can be reactivated 

**Current behaviour**: When u activate mechanism to active final boss  Archaedas in Ulduaman and defeat him u can activate mechanism again and spawn him again and farm xp and items on him

**Expected behaviour**: 1 mechanism activation 1 boss - no more spawning 

**Steps to reproduce the problem**:

1. 
2. 
3.

**Comment by NRG-Wow** [comment]
Fixed and it will be applied on next patch. Thanks for report!
