### ISSUE TITLE
[CATA][Spells][Paladin] Exorcism

### ISSUE THREAD

**Issue by Gubbyfishy** [NRG-Wow/NRGWow-Bugtracker#197]
(Probably a core issue, have fun)

**Reporter(Player/Character) Name**: Hundoslavus

**Description**: Exorcism cast during Art of War still resets the melee swing timer. It should not.

**Current behaviour**: Exorcism cast during Art of War still resets the melee swing timer.

**Expected behaviour**: Most instant spells cast from melee-type hybrid classes should never reset the melee swing timer (This is evident in the usage of Hammer of Justice, Cleanse, Hand of Freedom, etc.)

**Steps to reproduce the problem**:
1. Melee swing to proc Art of War
2. Stand next to target, target and cast Exorcism in melee
3. Wait X.XX seconds, depending on weapon attack speed.

Would not surprise me if Shamans suffer a similar issue with Maelstrom Weapon.

This was also fixed on some TrinityCores and is blizzlike behavior since 3.1 (For Art of War at least)
https://github.com/TrinityCore/TrinityCore/issues/1765

**Comment by virpyre** [comment]
The [Art of War](https://wow.gamepedia.com/The_Art_of_War) only gives your auto attacks a 20% chance to reset the cooldown of your Exorcism.

Confirmed. Instant abilities shouldn't disrupt the swing timer.

**Comment by hguy23** [comment]
Hotfixed applied. On next restart please re-test. Thanks.

**Comment by Gubbyfishy** [comment]
@frytik Nice, thank you! I'll keep an eye out.

**Comment by Gubbyfishy** [comment]
Working btw. @Wilcalaf

**Comment by hguy23** [comment]
:1st_place_medal:
