### ISSUE TITLE
[Cata][npc] Resurrection sickness

### ISSUE THREAD

**Issue by TeenWolf2** [NRG-Wow/NRGWow-Bugtracker#20]
[//]: #  (Only reports in english will be allowed. and specific issues. everything like "ZOMG NOTHING WORKS" will be ignored / deleted)

[//]: # (Please write the titles of the issues following the format:)
[//]: # ([CATA][Quests][Zones] Quest name)
[//]: # ([WOTLK][Spells][Classes] Spell name)
[//]: # ([WOTLK][Talents][Classes] Talent name)
[//]: # ([CATA][Glyphs][Classes] Glyph name)
[//]: # ([CATA][NPCs] NPC name)

**Reporter(Player/Character) Name**: Zoom

**Description**: When u activate respawn from Spirit (when u die ) he doesn't apply ressurection sickness 

**Current behaviour**: Stats dont get lowered 

**Expected behaviour**: Player should get resurrection sickness when resurrected by the spirit

**Steps to reproduce the problem**:

1. 
2. 
3.

**Comment by Wilcalaf** [comment]
Resurection sickness is configured to affect players only lvl 60 or above, thats intended.
Are you level 60 or above?

**Comment by TeenWolf2** [comment]
Im lower then 60 thanks for info
