### ISSUE TITLE
[CATA][Dungeon][The Oculus]

### ISSUE THREAD

**Issue by GajicMilos** [NRG-Wow/NRGWow-Bugtracker#200]
**Reporter(Player/Character) Name**:Velhaera

**Description**: Last boss isnt spawning, instead the loot is found as if he was already killed, and it can be looted, but is rendering Achievements for The Oculus undoable. Tried it twice, first 3 bosses are doable and fine, but the last one wont spawn.

**Comment by Wilcalaf** [comment]
Duplicate of #182
