### ISSUE TITLE
[CATA][World event][Stranglethorn Fishing Extravaganza]

### ISSUE THREAD

**Issue by GajicMilos** [NRG-Wow/NRGWow-Bugtracker#201]
**Reporter(Player/Character) Name**:Velhaera

**Description**: Tried fishing for Speckled Tastyfish today at 14:00 till 14:45, not a single one caught, with fishing skill around 580(even though it shouldnt be affected by fishing skill). At 14:45, asked in /world if anyone else is doing it, and nobody could catch a single Speckled Tastyfish. Once again its really for the Achievement, and maybe isnt as important, but i thought it should be known.

**Comment by Wilcalaf** [comment]
Indeed it should be known, thanks for report.

**Comment by Wilcalaf** [comment]
Hotfix has been applied on server to fix this.
please let us know if it happens again **after** next server restart
