### ISSUE TITLE
[CATA][Quests][Gilneas] Endgame

### ISSUE THREAD

**Issue by virpyre** [NRG-Wow/NRGWow-Bugtracker#207]
**Reporter Name**: Feralpyre

**Description**: Currently you get stuck on [Hippogryph](https://www.wowhead.com/npc=43747/hippogryph) unable to fly it or dismount getting an error message stating "you can't do that right now" in red text making you unable to complete [Endgame](https://www.wowhead.com/quest=26706/endgame).

**Current behaviour**: Currently when you click on a Hippogryph you can't dismount even when trying to click on the **Leave Vehicle** button, the Hippogryph also can't fly.
![2018-08-28 1](https://user-images.githubusercontent.com/41524551/44734224-5bc25680-aab7-11e8-8ef4-843ef3928b3e.png)

**Expected behaviour**:  [Endgame ID: 26706](https://www.youtube.com/watch?v=d3E_Tv8mBXA)

**Steps to reproduce the problem**:

1. .quest add 26706
2. Click on the hippogryph.
3. Press the "Space Bar" to Fly or try to "Leave Vehicle".

**Comment by Wilcalaf** [comment]
Duplcate of #137
