### ISSUE TITLE
([CATA][Quests][Zones] Rush Delivery

### ISSUE THREAD

**Issue by telemecus** [NRG-Wow/NRGWow-Bugtracker#21]
**Reporter(Player/Character) Name**:  Sitiria

**Description**: The Quest giver doesn't give this quest to keep going

**Current behaviour**:  You complete Fiver Upper and nothing after that

**Expected behaviour**:  The quest rush delivery should be available

**Steps to reproduce the problem**:

1. 
2. 
3.

**Comment by Wilcalaf** [comment]
This issue was specific to the player due to a crash while he was on the zone, otherwise the chain is working.
It was fixed by awarded him manually the quest.
