### ISSUE TITLE
[CATA][Core] "Can't do that while moving" issue

### ISSUE THREAD

**Issue by true-ede** [NRG-Wow/NRGWow-Bugtracker#210]
**Reporter(Player/Character) Name**: true-ede

**Description**:  When trying to do something (for example farm a node or craft something) while mounted on a flying mount and standing on the ground, the game throws a "Can't do that while moving" message. Have to click again for the action to be performed. This is a minor, quality of life type of issue as this was not happening before, makes farming somewhat annoying. 

**Current behaviour**:  Character dismounts but action isn't started while on the ground on a flying mount, have to click again

**Expected behaviour**: Character dismounting and desired action performed right away while on the ground on a flying mount

**Steps to reproduce the problem**:

1. Mount up on a flying mount
2. Try to farm a node while landing on the ground or try to craft something on the ground while sitting on the mount

**Comment by Wilcalaf** [comment]
@frytik Look like this started from the patch that fixed this #155

**Comment by Wilcalaf** [comment]
@true-ede Should be working ok now.
please retest when you can

**Comment by true-ede** [comment]
@Wilcalaf Works correctly now, thanks!
