### ISSUE TITLE
([CATA][Quests][Zones] Reactivate the Constructs

### ISSUE THREAD

**Issue by telemecus** [NRG-Wow/NRGWow-Bugtracker#23]
**Reporter(Player/Character) Name**: Sitiria

**Description**:  Reactivate 5 Deactivated War Constructs

**Current behaviour**: Nothing they just tell you Greetings

**Expected behaviour**:  Be able to click on them or in the dialogue Box to be able to activate them

**Steps to reproduce the problem**:

1.  
2. 
3.

**Comment by Wilcalaf** [comment]
Thanks for report all of Deepholm zone will get totally rewrited soon.

**Comment by Wilcalaf** [comment]
Also, this quest was fixed after the restart that was done to fix a global issue not letting multiple quest to be completed ( deepholm is still getting totally rewrited soon)
