### ISSUE TITLE
[EN][Cata][Mechanic] Resurrect Timer

### ISSUE THREAD

**Issue by Illusie** [NRG-Wow/NRGWow-Bugtracker#24]
[//]: #  (Only reports in english will be allowed. and specific issues. everything like "ZOMG NOTHING WORKS" will be ignored / deleted)

**Reporter(Player/Character) Name**: ---

**Description**: When you die and spawn on Graveyard, and after you run your Corpse.
you should recieve a Timer for resurrect, up to maximum 2 mins.

**Current behaviour**: when you reach your Corpse you recieve "Ressurect Now" Message immediately.

**Expected behaviour**: wrote above ^ I'm not sure about the Timers. but I know the max is 2min.

**Steps to reproduce the problem**:
1. die, run your corpse. look at the message.
2. 
3.

source:
https://wow.gamepedia.com/Resurrect
After dying there is a time in which you can not return to your body or accept the resurrection cast by another player. This is known as the "Resurrection Cooldown" (not to be confused with the cooldowns on engineering, combat, and mass resurrection abilities). This timer increases with each death to a maximum of 2 minutes. This timer does not affect resurrection at a Spirit Healer or instance portal.

**Comment by Wilcalaf** [comment]
The resurection time is based on the amount of times you died in a lapse of time, it wont be 2 minutes the first time you have to die a few times in a certain period of time for it to be increased and reaching a maximum of 2 minutes.

**Comment by Illusie** [comment]
You always recieve 'Ressurect Now' message in game, atleast to from what I saw.

**Comment by Illusie** [comment]
I think its fixed I sometimes recieve 24 sec timer.
closed.
