### ISSUE TITLE
[EN][Cata][Eastern Kingdoms][Swamp of Sorrows][Quest] Can't Take It With Them

### ISSUE THREAD

**Issue by Illusie** [NRG-Wow/NRGWow-Bugtracker#25]
[//]: #  (Only reports in english will be allowed. and specific issues. everything like "ZOMG NOTHING WORKS" will be ignored / deleted)

**Reporter(Player/Character) Name**: ----

**Description**: Quest doesn't work

**Current behaviour**: Screenshot: https://imgur.com/a/5WGUMwI

**Expected behaviour**: What should happen instead
https://www.youtube.com/watch?v=wLpjielqE6o
https://www.youtube.com/watch?v=jlQwx2GOZkI

**Steps to reproduce the problem**:

1. pick quest go to NPC and click it. 
2. 
3.

**Comment by Wilcalaf** [comment]
Quest will be working after a restart

**Comment by Wilcalaf** [comment]
Quest is working now after restart
