### ISSUE TITLE
[EN][Cata][Eastern Kingdoms][Swamp of Sorrows][Quest] In With a Bang

### ISSUE THREAD

**Issue by Illusie** [NRG-Wow/NRGWow-Bugtracker#26]
[//]: #  (Only reports in english will be allowed. and specific issues. everything like "ZOMG NOTHING WORKS" will be ignored / deleted)

**Reporter(Player/Character) Name**: ---

**Description**: Quest not working, speak with the NPC nothing happen.

**Current behaviour**: Screenshot: https://imgur.com/a/cX5xOPT

**Expected behaviour**: 
https://www.youtube.com/watch?v=hF9a-m5hLU0

**Steps to reproduce the problem**:

1.  pick quest, talk to NPC and look.
2. 
3.

**Comment by Wilcalaf** [comment]
restart didnt affect this one. it will be fixed in the future when we reach this zone rewrite.
We have planned full rewrite for all questing zones.
