### ISSUE TITLE
[Cata][Dungeon] Random high level mobs guarding Deadmines

### ISSUE THREAD

**Issue by Gooberter** [NRG-Wow/NRGWow-Bugtracker#3]
Just a random skull mob killing us so we cant even do the first dungeon. Was this ever tested once?

**Comment by Wilcalaf** [comment]
Can you please provide screenshot or name of the Mob?

**Comment by Wilcalaf** [comment]
After some reasearch its been discovered that you have most likely talking about the alliance or the horde quest givers that are there. it will be fixed after next maintenance
