### ISSUE TITLE
[CATA][General] Sending items via Mailbox bugged

### ISSUE THREAD

**Issue by TeenWolf2** [NRG-Wow/NRGWow-Bugtracker#31]
[//]: #  (Only reports in english will be allowed. and specific issues. everything like "ZOMG NOTHING WORKS" will be ignored / deleted)

[//]: # (Please write the titles of the issues following the format:)
[//]: # ([CATA][Quests][Zones] Quest name)
[//]: # ([WOTLK][Spells][Classes] Spell name)
[//]: # ([WOTLK][Talents][Classes] Talent name)
[//]: # ([CATA][Glyphs][Classes] Glyph name)
[//]: # ([CATA][NPCs] NPC name)

**Reporter(Player/Character) Name**: Zoom

**Description**: My friend (Gutsy) sent me and item some low lvl dagger via mailbox and i never received it , i didn't even receive notification on mini map.

**Current behaviour**: Mails are not sending right , items never get to player etc... EDIT: (mail was sent 30 minutes ago , and i didnt got it , i asked players on world chat they told me mailbox items arrive in 1 hour , so i guess sending time is problem )

**Expected behaviour**: Player who received mail with item should be able to see it and should be able to receive it 

**Steps to reproduce the problem**:

1. 
2. 
3.

**Comment by Wilcalaf** [comment]
Hey, The time of mail arrival between players is supposed to be 1 hour.
The icon will eventually show up after a while. there is a small bug that sometimes if you get too many items or checked the mailbox recently you wont see the next icon until relog or 10-15 minutes.
