### ISSUE TITLE
[CATA][Dungeon] Scarlet Armory 

### ISSUE THREAD

**Issue by TeenWolf2** [NRG-Wow/NRGWow-Bugtracker#36]
[//]: #  (Only reports in english will be allowed. and specific issues. everything like "ZOMG NOTHING WORKS" will be ignored / deleted)

[//]: # (Please write the titles of the issues following the format:)
[//]: # ([CATA][Quests][Zones] Quest name)
[//]: # ([WOTLK][Spells][Classes] Spell name)
[//]: # ([WOTLK][Talents][Classes] Talent name)
[//]: # ([CATA][Glyphs][Classes] Glyph name)
[//]: # ([CATA][NPCs] NPC name)

**Reporter(Player/Character) Name**: Zoom

**Description**: When final boss killed players dont receive reward from rdf and if leave they get deserter status
**Current behaviour**: Rdf doesn't give reward and when players have killed all bosses and if they leave after it they get deserter status 

**Expected behaviour**: What should happen instead

**Steps to reproduce the problem**:

1. 
2. 
3.

**Comment by Wilcalaf** [comment]
Thanks for report it will be fixed after next patch

**Comment by Wilcalaf** [comment]
Fixed on this patch
