### ISSUE TITLE
[CATA][Quests][Zones] The Voice of Goldrinn

### ISSUE THREAD

**Issue by djsaltynuts** [NRG-Wow/NRGWow-Bugtracker#37]
[//]: #  (Only reports in english will be allowed. and specific issues. everything like "ZOMG NOTHING WORKS" will be ignored / deleted)

[//]: # (Please write the titles of the issues following the format:)
[//]: # ([CATA][Quests][Zones] Quest name)
[//]: # ([WOTLK][Spells][Classes] Spell name)
[//]: # ([WOTLK][Talents][Classes] Talent name)
[//]: # ([CATA][Glyphs][Classes] Glyph name)
[//]: # ([CATA][NPCs] NPC name)

**Reporter(Player/Character) Name**: Raw

**Description**: Appears that you don't get into the correct phase in the shrine of goldrinn when taking the quest

**Current behaviour**: Phasing is wrong, no NPCs at all in the shrine of goldrinn

**Expected behaviour**: The player should end up in the right phasing once the quest is accepted

**Steps to reproduce the problem**: Take the quest from the NPC, walk down to the shrine of goldrinn and have a gander.

On the subject of things more quests in the shrine of goldrinn area seem to also be locked behind some phasing issues.

**Comment by Wilcalaf** [comment]
Thanks for report, please open in game ticket to get assitance until we can fix this

**Comment by NRG-Wow** [comment]
It seems to be a specific issue with this player because all the rest are doing the chain fine.
if you havent, please open a ticket to get a gm to help you or request help on discord
thanks!
