### ISSUE TITLE
[Cata][Dungeon] Admiral Ripsnarl in Deadmines hits for 10k at lvl 20!

### ISSUE THREAD

**Issue by Anatarage** [NRG-Wow/NRGWow-Bugtracker#4]
Admiral Ripsnarl hit me for 10k at level 20...

**Comment by Wilcalaf** [comment]
The issue was reproduced with the Vapors reaching to the point were they one shot.
the dungeon has been adapted for low lvls to get less vapors so they can kill them before they do ton of damage and will be applied on next Patch

**Comment by NRG-Wow** [comment]
The issue will be fixed on next patch
