### ISSUE TITLE
[Cata][Quest][Fellwood] Twin temptresses

### ISSUE THREAD

**Issue by TeenWolf2** [NRG-Wow/NRGWow-Bugtracker#42]
[//]: #  (Only reports in english will be allowed. and specific issues. everything like "ZOMG NOTHING WORKS" will be ignored / deleted)

[//]: # (Please write the titles of the issues following the format:)
[//]: # ([CATA][Quests][Zones] Quest name)
[//]: # ([WOTLK][Spells][Classes] Spell name)
[//]: # ([WOTLK][Talents][Classes] Talent name)
[//]: # ([CATA][Glyphs][Classes] Glyph name)
[//]: # ([CATA][NPCs] NPC name)

**Reporter(Player/Character) Name**: Zoom

**Description**: Quest cant be done

**Current behaviour**: In quest named above a player should kill 2 npcs but at the location of those npcs , u cant see them , i used /target Salia etc.. and i could target her at the location but i think she fell down in map

**Expected behaviour**: Npcs should be on the ground 

**Steps to reproduce the problem**:

1. 
2. 
3.

**Comment by NRG-Wow** [comment]
The quest is working, you probably didnt find them because they are indeed in a cave underground called "The shadow hold"
please check comments on wowhead to understand where they are exactly
http://www.wowhead.com/quest=28131/twin-temptresses
