### ISSUE TITLE
[CATA][Talents][Warrior]Second Wind]

### ISSUE THREAD

**Issue by Kipale** [NRG-Wow/NRGWow-Bugtracker#43]
[//]: #  (Only reports in english will be allowed. and specific issues. everything like "ZOMG NOTHING WORKS" will be ignored / deleted)

[//]: # (Please write the titles of the issues following the format:)
[//]: # ([CATA][Quests][Zones] Quest name)
[//]: # ([WOTLK][Spells][Classes] Spell name)
[//]: # ([WOTLK][Talents][Classes] Talent name)
[//]: # ([CATA][Glyphs][Classes] Glyph name)
[//]: # ([CATA][NPCs] NPC name)

**Reporter(Player/Character) Name**:
Kipale
**Description**: Describe the problem
Second wind doesn't proc from stun or snare
**Current behaviour**: What happens
Nothing
**Expected behaviour**: What should happen instead
Second wind should proc
**Steps to reproduce the problem**:
Fix it
1. 
2. 
3.

**Comment by Wilcalaf** [comment]
![image](https://user-images.githubusercontent.com/9047365/43049063-3d34306e-8dfa-11e8-9411-e12369a20e49.png)
I could not reproduce, can you be more specific on how and where it happened?

**Comment by Wilcalaf** [comment]
I cannot reproduce the issue, if you have a more specific scenario where it didnt happen please reopen it with more details
![image](https://user-images.githubusercontent.com/9047365/43049140-547b8af0-8dfb-11e8-9304-b799ec34443a.png)
