### ISSUE TITLE
[Cata][General] Orgrimars portal to blasted lands

### ISSUE THREAD

**Issue by TeenWolf2** [NRG-Wow/NRGWow-Bugtracker#45]
[//]: #  (Only reports in english will be allowed. and specific issues. everything like "ZOMG NOTHING WORKS" will be ignored / deleted)

[//]: # (Please write the titles of the issues following the format:)
[//]: # ([CATA][Quests][Zones] Quest name)
[//]: # ([WOTLK][Spells][Classes] Spell name)
[//]: # ([WOTLK][Talents][Classes] Talent name)
[//]: # ([CATA][Glyphs][Classes] Glyph name)
[//]: # ([CATA][NPCs] NPC name)

**Reporter(Player/Character) Name**: Zoom

**Description**: Portal to blasted lands cant be used
**Current behaviour**: when player clicks on orgrimars portal to blasted lands(dark portal) it says Target is locked for another instance

**Expected behaviour**: When player clicks to portal it should instantly take him to blasted lands

**Steps to reproduce the problem**:

1. 
2. 
3.

**Comment by Wilcalaf** [comment]
I cannot reproduce this, 
tested on both portals in orgrimmar (cleft of shadow and valey of spirits)
were you in party or in lfg group or someting of any kind?

**Comment by TeenWolf2** [comment]
I had some bug on me, being stuck in rdf party even after leaving thats what was keeping me from using dark portal , jeff helped me all good now thanks :)
