### ISSUE TITLE
[EN][Cata][Northrend][Zul'Drak][Quests] In Search of Answers

### ISSUE THREAD

**Issue by Illusie** [NRG-Wow/NRGWow-Bugtracker#50]
[//]: #  (Only reports in english will be allowed. and specific issues. everything like "ZOMG NOTHING WORKS" will be ignored / deleted)

**Reporter(Player/Character) Name**: ---

**Description**: can't complete the Quest. / Unclickable
causing all quest-chain and followed quests to not appear.

**Current behaviour**: ^

**Expected behaviour**: https://www.youtube.com/watch?v=PzX72gQRz-o

**Steps to reproduce the problem**: 

1. follow video
2. 
3.

P.S
all the quest pick there are bugged.

**Comment by NRG-Wow** [comment]
Thanks for report, it will be fixed on next restart
