### ISSUE TITLE
[CATA][DUNGEON][TBC][DROPS] No Netherweave Cloth dropping in HF or BF Normal

### ISSUE THREAD

**Issue by Hatharis** [NRG-Wow/NRGWow-Bugtracker#51]
https://www.youtube.com/watch?v=Jrcq0X94gFw

I also used to do it myself on retail

**Comment by hguy23** [comment]
Fix done. Today will be fixed. Thanks for report.

**Comment by NRG-Wow** [comment]
This has been fixed and will be applied on nex tpatch
