### ISSUE TITLE
[Cata[[RedRidge] Black Dragon Whelp ID 441

### ISSUE THREAD

**Issue by TheRealestMcCoy** [NRG-Wow/NRGWow-Bugtracker#52]
**Reporter(Player/Character) Name**:

**Description**: Describe the problem
They where removed from RR in cata
**Current behaviour**: What happens

**Expected behaviour**: What should happen instead
They should not be in the zone
**Steps to reproduce the problem**:

1. go to RR and look aorund
2.  they are spawned in as if its pre cata 
3.

http://www.wowhead.com/search?q=black+dragon+whelp

**Comment by NRG-Wow** [comment]
Hey there, do you have any reference that shows they have in fact been removed?.

EDIT: I found.

thanks for report they will be removed on next update
