### ISSUE TITLE
[Cata][Redridge] Dire Condor ID 428

### ISSUE THREAD

**Issue by TheRealestMcCoy** [NRG-Wow/NRGWow-Bugtracker#53]
**Description**: Describe the problem
Using pre cata models
**Current behaviour**: What happens
pre cata models
**Expected behaviour**: What should happen instead
use new cata models
**Steps to reproduce the problem**:

1. go to RR look at dire condors.
2. 
3.
http://www.wowhead.com/npc=428/dire-condor

**Comment by TheRealestMcCoy** [comment]
REPLACE INTO `creature_template` (`entry`, `difficulty_entry_1`, `difficulty_entry_2`, `difficulty_entry_3`, `KillCredit1`, `KillCredit2`, `modelid1`, `modelid2`, `modelid3`, `modelid4`, `name`, `subname`, `IconName`, `gossip_menu_id`, `minlevel`, `maxlevel`, `exp`, `exp_unk`, `faction_A`, `faction_H`, `npcflag`, `speed_walk`, `speed_run`, `speed_swim`, `speed_fly`, `scale`, `rank`, `mindmg`, `maxdmg`, `dmgschool`, `attackpower`, `dmg_multiplier`, `baseattacktime`, `rangeattacktime`, `unit_class`, `unit_flags`, `unit_flags2`, `dynamicflags`, `family`, `trainer_type`, `trainer_spell`, `trainer_class`, `trainer_race`, `minrangedmg`, `maxrangedmg`, `rangedattackpower`, `type`, `type_flags`, `type_flags2`, `lootid`, `pickpocketloot`, `skinloot`, `resistance1`, `resistance2`, `resistance3`, `resistance4`, `resistance5`, `resistance6`, `spell1`, `spell2`, `spell3`, `spell4`, `spell5`, `spell6`, `spell7`, `spell8`, `PetSpellDataId`, `VehicleId`, `mingold`, `maxgold`, `currencyId`, `currencyCount`, `AIName`, `MovementType`, `InhabitType`, `HoverHeight`, `Health_mod`, `Mana_mod`, `Mana_mod_extra`, `Armor_mod`, `RacialLeader`, `questItem1`, `questItem2`, `questItem3`, `questItem4`, `questItem5`, `questItem6`, `movementId`, `RegenHealth`, `equipment_id`, `mechanic_immune_mask`, `flags_extra`, `ScriptName`) VALUES (428, 0, 0, 0, 0, 0, 23482, 0, 0, 0, 'Dire Condor', '', '', 0, 15, 16, 0, 0, 2200, 2200, 0, 1, 1.14286, 1, 1, 1, 0, 27, 37, 0, 68, 1, 2000, 2000, 1, 0, 2048, 2048, 7, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 428, 0, 0, 0, 0, 0, 0, 0, 0, 17253, 2649, 3427, 0, 0, 0, 0, 0, 12877, 0, 0, 0, NULL, NULL, 'SmartAI', 1, 4, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 428, 0, 0, '');

**Comment by TheRealestMcCoy** [comment]
`REPLACE INTO `creature_template` (`entry`, `difficulty_entry_1`, `difficulty_entry_2`, `difficulty_entry_3`, `KillCredit1`, `KillCredit2`, `modelid1`, `modelid2`, `modelid3`, `modelid4`, `name`, `subname`, `IconName`, `gossip_menu_id`, `minlevel`, `maxlevel`, `exp`, `exp_unk`, `faction_A`, `faction_H`, `npcflag`, `speed_walk`, `speed_run`, `speed_swim`, `speed_fly`, `scale`, `rank`, `mindmg`, `maxdmg`, `dmgschool`, `attackpower`, `dmg_multiplier`, `baseattacktime`, `rangeattacktime`, `unit_class`, `unit_flags`, `unit_flags2`, `dynamicflags`, `family`, `trainer_type`, `trainer_spell`, `trainer_class`, `trainer_race`, `minrangedmg`, `maxrangedmg`, `rangedattackpower`, `type`, `type_flags`, `type_flags2`, `lootid`, `pickpocketloot`, `skinloot`, `resistance1`, `resistance2`, `resistance3`, `resistance4`, `resistance5`, `resistance6`, `spell1`, `spell2`, `spell3`, `spell4`, `spell5`, `spell6`, `spell7`, `spell8`, `PetSpellDataId`, `VehicleId`, `mingold`, `maxgold`, `currencyId`, `currencyCount`, `AIName`, `MovementType`, `InhabitType`, `HoverHeight`, `Health_mod`, `Mana_mod`, `Mana_mod_extra`, `Armor_mod`, `RacialLeader`, `questItem1`, `questItem2`, `questItem3`, `questItem4`, `questItem5`, `questItem6`, `movementId`, `RegenHealth`, `equipment_id`, `mechanic_immune_mask`, `flags_extra`, `ScriptName`) VALUES (428, 0, 0, 0, 0, 0, 23482, 0, 0, 0, 'Dire Condor', '', '', 0, 15, 16, 0, 0, 2200, 2200, 0, 1, 1.14286, 1, 1, 1, 0, 27, 37, 0, 68, 1, 2000, 2000, 1, 0, 2048, 2048, 7, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 428, 0, 0, 0, 0, 0, 0, 0, 0, 17253, 2649, 3427, 0, 0, 0, 0, 0, 12877, 0, 0, 0, NULL, NULL, 'SmartAI', 1, 4, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 428, 0, 0, '');
`

**Comment by NRG-Wow** [comment]
Thanks for help, we'll see the verified and implemented

**Comment by NRG-Wow** [comment]
Thanks, it will be applied on next server update

**Comment by hguy23** [comment]
Great help. But next time do first delete from and then insert into.
