### ISSUE TITLE
[Cata][Core] Class Mounts

### ISSUE THREAD

**Issue by TheRealestMcCoy** [NRG-Wow/NRGWow-Bugtracker#54]
**Reporter(Player/Character) Name**:

**Description**: Describe the problem
I did not learn apprentice riding when i learned my level 20 mount from class trainer.
**Current behaviour**: What happens
I learned the paladin mount from the class trainer but did not learn apprentice riding
**Expected behaviour**: What should happen instead
All classes that have a class mount should learn apprentice riding apon learning the levle 20 clas smount. This includes the Paladin, Warlock, even a Worgen 
**Steps to reproduce the problem**:

1. reach level 20
2. go to class trainer
3.learn class mount
4.cant mount
5.check spell book
6.apprentice riding not learned.

http://www.wowhead.com/spell=33388/apprentice-riding

Class-specific Information / Worgens
Classes which have exclusive, non-epic ground mounts automatically learn Apprentice Riding upon reaching level 20. As a result, they do not have to train Apprentice Riding from a Riding Trainer like other classes. They are then able to train their class-specific mount from their class trainer.
Warlocks are automatically granted Apprentice Riding upon reaching level 20. They also gain  Felsteed.
Paladins are automatically granted Apprentice Riding upon reaching level 20. They also gain  Summon Warhorse ( Human/ Dwarf),  Summon Thalassian Warhorse (Blood Elf),  Summon Exarch's Elekk ( Draenei) or  Summon Sunwalker Kodo ( Tauren).
 Worgen players are automatically granted Apprentice Riding at level 20, as well, due to their racial ability  Running Wild.

**Comment by NRG-Wow** [comment]
Confirmed.
thanks for report

**Comment by hguy23** [comment]
Rewriting it

**Comment by hguy23** [comment]
Fixed on next restart. :100:
