### ISSUE TITLE
[CATA][Daily - Cooking][Orgrimmar]

### ISSUE THREAD

**Issue by virpyre** [NRG-Wow/NRGWow-Bugtracker#58]
**Reporter(Player/Character) Name**: Cule

**Description**: Player said that they were unable to turn in Daily Cooking Quests because the button was greyed out on the quest, even though they had all the items in inventory. Tried using the .quest complete command to complete quest player said they got a Quest Complete notification but still couldn't turn them into the NPC.

**Current behaviour**:  Unable to turn in Daily Cooking Quests with items or using .quest complete command.

**Expected behaviour**:  You should be able to turn the quests in if you have all of the items in your inventory or .quest complete command.

**Steps to reproduce the problem**:

1.  Take the quests [Everything Is Better with Bacon](http://www.wowhead.com/quest=26220/everything-is-better-with-bacon), [Even Thieves Get Hungry](http://www.wowhead.com/quest=26235/even-thieves-get-hungry), [Crawfish Creole](http://www.wowhead.com/quest=26226/crawfish-creole).
2. For GM use the command .additem 57758 6, .additem 57879 3 and .additem 57765 10.
3. Try to turn in [Marogg](http://www.wowhead.com/npc=42506/marogg)

**Comment by NRG-Wow** [comment]
I cant reproduce the issue.
Are you sure the player had space in the inventory?
or that he havent finish his daily quest maximum completed per day?
https://gyazo.com/315d28446a94f57463c60b89d7890760
https://gyazo.com/5a3e2eb1d18330965183e37eb3f94b41

**Comment by virpyre** [comment]
Chef's Reward doesn't take up space in the inventory, it's on the character tab.

Cule said that she got all 3 of those quests at the same time on the same day. She also said that they were her first daily quests.

**Comment by NRG-Wow** [comment]
Not the reward, im speaking about the necesarry items to complete the quests.
I tried it again regulary and it looks working
Can you try it on yourself too so we can verify if its a specific user issue or a server problem?

**Comment by virpyre** [comment]
I can conquer that all quests are working as well, I don't know what was up with the player maybe he reached his daily cap.
