### ISSUE TITLE
[CATA][NPCs] Npcs - Water

### ISSUE THREAD

**Issue by TeenWolf2** [NRG-Wow/NRGWow-Bugtracker#6]
[//]: #  (Only reports in english will be allowed. and specific issues. everything like "ZOMG NOTHING WORKS" will be ignored / deleted)

[//]: # (Please write the titles of the issues following the format:)
[//]: # ([CATA][Quests][Zones] Quest name)
[//]: # ([WOTLK][Spells][Classes] Spell name)
[//]: # ([WOTLK][Talents][Classes] Talent name)
[//]: # ([CATA][Glyphs][Classes] Glyph name)
[//]: # ([CATA][NPCs] NPC name)

**Reporter(Player/Character) Name**: Zoom

**Description**: When u kill npc in water , he falls down to the ground , this can be problem in zones like Vashj'ir
**Current behaviour**: Npcs fall all the way down to the ground

**Expected behaviour**: npcs should remain on location where they were killed 

**Steps to reproduce the problem**:

1. 
2. 
3.

**Comment by NRG-Wow** [comment]
This has been fixed as part of the Movement and pathgeneration rewrite and will be applied on next patch!
