### ISSUE TITLE
[EN][Cata][Core] Cataclysm Portals

### ISSUE THREAD

**Issue by Illusie** [NRG-Wow/NRGWow-Bugtracker#62]
[//]: #  (Only reports in english will be allowed. and specific issues. everything like "ZOMG NOTHING WORKS" will be ignored / deleted)

**Reporter(Player/Character) Name**: ---

**Description**: The portals to Hyjal, Uldum, Deepholm, Vash'jir, Twillight Highlands
should not be automiatic opened you need to do Quest-lines to open those Portals.

**Current behaviour**: They already open.

**Expected behaviour**: ^ explained above.

**Steps to reproduce the problem**:

1. go to portal positions in Stormwind take portals to each zone.
2.  don't know if on Orgrimmar it is the same didn't checked.

**Comment by NRG-Wow** [comment]
Thanks for report however this has been done in purpose due to inconvenienced that can be cause by high rates
