### ISSUE TITLE
[CATA][Quests][Eversong Woods] Unexpected Results

### ISSUE THREAD

**Issue by DemoXinMC** [NRG-Wow/NRGWow-Bugtracker#65]
The mobs required for the quest completion do not spawn in waves, and instead spawn clustered nearby the NPC that requires protection all at once, making completing this quest at level near-impossible.

**Comment by NRG-Wow** [comment]
Thanks for report, until this is fixed please make an ingame ticket for assistance

**Comment by hguy23** [comment]
Taking it, today will be fixed.

**Comment by NRG-Wow** [comment]
It has been fixed on last update, thanks!
