### ISSUE TITLE
[EN][Priest] Power Word: Shield

### ISSUE THREAD

**Issue by Illusie** [NRG-Wow/NRGWow-Bugtracker#69]
[//]: #  (Only reports in english will be allowed. and specific issues. everything like "ZOMG NOTHING WORKS" will be ignored / deleted)

**Reporter(Player/Character) Name**: ----

**Description**: Power Word: Shield does overscale Absorb amount.

**Current behaviour**: Too lazy to actually trying to do the math behind it.
I just "felt" Shield is giving more absorb than it should.

Last time I tested it I had 4989 spellpower (lets say 5k) not sure about Mastery % (I changed gear items)
and my PW:S gave 22k Absorb.

I said it is about myself "feeling" just for comparsion In Firelands my Priest had around 10k SP and I believe my PS:W was around 26-28k.
in DS  my priest does around 33k-34k PW:S
And I have alot more Mastery.

so 22k shield make no sense to me.

**Expected behaviour**: Proper amount of PW:S Absorb giving.

**Steps to reproduce the problem**:

1.  https://cata-twinhead.twinstar.cz/?issue=16528&highlight=power%20word
this is the only link I actually searched and looked for.

Sadly there alot bugs and quantity takes over quality and sources.

**Comment by virpyre** [comment]
Formula for calculation for PWS = (Base+(SP*(coeff+BT)))*(1+TD)*(1+FP)*(1+IPWS).

**Comment by Illusie** [comment]
https://imgur.com/a/7Dohkea

above one is another server (reference)
below one is NRG server. 

as I said im too lazy to do maths ; ) its just feeling that PW:S is overscaled on NRG.

P.S
as I said many times I dont take other pservers as the 'completely truth'. maybe you right and they are wrong. who knows :)

**Comment by virpyre** [comment]
Okay, so **First Server** you have 11429 SP, with a Boost of 47% from Mastery. Your normal shield would be able to absorb 29,578. If you have the Glyph that adds another 5,916 the max amount of damage that can be absorbed before the shield dissipates, is 35,494.

On **NRG Server** you have 4497 SP, with a Boost of 28% from Mastery. Your normal shield would be able to absorb 12,308. If you have the Glyph that adds another 2,462 the max amount of damage that can be absorbed before the shield dissipates, is 14,770.

There is an overall difference of 58% of the total server to nrg, from what I can see.

**Comment by Illusie** [comment]
@virpyre which glyph you mean?
the only glyph that up in my mind is Glyph of Power Word: Shield which not increasing the absorbtion amount.

"your PW:S also **heals** the target for 20% of the absorbtion amount".

just for another comparsion i emptied my character (wore off items) for base stats.
230 SP, 8:00 mastery (0%) only Inner Will used I got 12725 shield absorb.

on NRG same base stats gave me 12371.

.........
well I take everything I said back ........ that or your PW:S is overscaled or it downscaled can't be sure at this moment totally confused.

Ill leave the messages w/o deleting them for next 30min.

**Comment by virpyre** [comment]
Disregard the post above the formula was for WoTLK.

For Cata, it is either _Spell power * 1.54 * (1 + Spirit) * 1 * 1_ or something else...

**OTHER** 11429 x 1.54 x (1 + Spirit) x 1 x 1 = Shield
**NRG** 4497 x 1.54 x (1 + Spirit) x 1 x 1 = Shield

**Comment by virpyre** [comment]
Average for this TEST Priest 298k, Mastery is 15.89 which gives 39%...max is 376k.

**Comment by Illusie** [comment]
formula taken from simc 4.3.4

absorbing $<shield> damage$?s55672[ and healing them for $55672s1% of the absorption amount]

Variables    : $twin1=$?s47586[${1.02}][${1.00}]
$twin2=$?s47587[${1.04}][${$<twin1>}]
$twin3=$?s47588[${1.06}][${$<twin2>}]
$ipws1=$?s14748[${1.10}][${1.00}]
$ipws2=$?s14768[${1.20}][${$<ipws1>}]
$mastery=$?s47540[${((100+$77484m1)/100)}][${1.00}]
$spirit=$?s87336[${((100+$87336m1)/100)}][${1.00}]
$shield=${((($SP*0.87)+$m1)*$<mastery>*$<spirit>*$<twin3>*$<ipws2>)}

Ill close this issue too.
