### ISSUE TITLE
[CATA][Dungeon] - Leave dungeon button on RDF not working

### ISSUE THREAD

**Issue by TeenWolf2** [NRG-Wow/NRGWow-Bugtracker#7]
[//]: #  (Only reports in english will be allowed. and specific issues. everything like "ZOMG NOTHING WORKS" will be ignored / deleted)

[//]: # (Please write the titles of the issues following the format:)
[//]: # ([CATA][Quests][Zones] Quest name)
[//]: # ([WOTLK][Spells][Classes] Spell name)
[//]: # ([WOTLK][Talents][Classes] Talent name)
[//]: # ([CATA][Glyphs][Classes] Glyph name)
[//]: # ([CATA][NPCs] NPC name)

**Reporter(Player/Character) Name**: Zoom

**Description**: "teleport out of dungeon " option doesent work

**Current behaviour**: When u click on teleport out of dungeon (from minimap dungeon icon) it just reloads and u are still in instance 

**Expected behaviour**: Take player to the location they were before entering dungeon

**Steps to reproduce the problem**:

1. 
2. 
3.

**Comment by hguy23** [comment]
Taking a look at it.

**Comment by hguy23** [comment]
Fixed
