### ISSUE TITLE
Problems with conquest points !

### ISSUE THREAD

**Issue by shimura1995** [NRG-Wow/NRGWow-Bugtracker#73]
Shimura, from nrg-cata

Hello there, i got an issue with conquest points earned with arena Queue.. I never got the points when win!, and others win points normally my team earn too when we won and i still got 0 :(.. could u help me out checking it? im going off until the saturday, ill answer that day. We test with a new team, changing with other player, me the leader of the team, deleting cache, I dont know what else but we try and nothing happen, still 0 conquest earn. Thank you for your time.

**Comment by NRG-Wow** [comment]
Hey there i have fixed it for your character, please next time for this kind of user specific issue is better if you just open an ingame ticket or request support on discord
anyway your issue shall be solved now, please relog and try again
