### ISSUE TITLE
Battlegrounds EXP

### ISSUE THREAD

**Issue by Nadiirr** [NRG-Wow/NRGWow-Bugtracker#77]
**Reporter(Player/Character) Name**:

**Description**: Battlegrounds do not give any exp.

**Current behaviour**: Battlegrounds do not give exp. 

**Expected behaviour**: Battlegrounds should give exp. (More for a win.)

**Comment by Wilcalaf** [comment]
This has been fixed and will be applied on next maintenance, thanks for report!

**Comment by Wilcalaf** [comment]
Looks like under a certain level its still not working
-- Update
Issue spotted, they were implemented only for  Random BG and not specific ones.

**Comment by Wilcalaf** [comment]
This has been fixed locally and will be applied on next maintenance.
