### ISSUE TITLE
[EN][Core] Alliance & Horde Group Que together into Battleground.

### ISSUE THREAD

**Issue by Illusie** [NRG-Wow/NRGWow-Bugtracker#82]
[//]: #  (Only reports in english will be allowed. and specific issues. everything like "ZOMG NOTHING WORKS" will be ignored / deleted)

**Reporter(Player/Character) Name**: ----

**Description**: Since server is crossfaction BGs/Raids/Arenas etc.
me and my friend tried to Que together (in group) to BG and we couldn't.
we could've together in group but not to queue.

**Current behaviour**: getting red message middle screen "name was unavailable to join the queue"

**Expected behaviour**: If the server is crossfactioned and people can be in same guild and group so they should also que together (?)

**Steps to reproduce the problem**:

1. 
2. 
3.

**Comment by hguy23** [comment]
Duplicate https://github.com/NRG-Wow/NRGWow-Bugtracker/issues/122

**Comment by Illusie** [comment]
oh crap I duplicated myself ^^ thought I didn't reported it lol.
Anywhy I prefer the newest one, I closed this.
@frytik

**Comment by Elannreportujerzeczy** [comment]
plz fix asap :D
