### ISSUE TITLE
[EN][Cata] Pets & Walking paths

### ISSUE THREAD

**Issue by Illusie** [NRG-Wow/NRGWow-Bugtracker#83]
[//]: #  (Only reports in english will be allowed. and specific issues. everything like "ZOMG NOTHING WORKS" will be ignored / deleted)

**Reporter(Player/Character) Name**: ----

**Description**: Not sure tho, again I ain't searched for sources, Just from my memories.
When you mount up. your pet(s) should disappear and not follow you.
when you mount down. your pet(s) appear back.

**Current behaviour**: atm, when you mount up your pet is not disappearing.
causing pet stuck / not following you and also (might) can cause disappearing then you need summon again. (im not sure) cause im not playing Pet class.

But here is 2 screenshots taken from BGs about how wrong is the pets atm.
https://imgur.com/a/CQrZQVO

blue circle - pet, red circle - where hunter is.

note that I didn't Arena yet so I do not know how the walkpaths inside Arenas.

**Expected behaviour**: As far I know when you mount up your pet should disappear
when you mount down he should appear again.

**Steps to reproduce the problem**:

1.  sorry for not searching sources.
2. 
3.

**Comment by NRG-Wow** [comment]
Pets will disappear when mounting and reappear when dismounting after next patch
