### ISSUE TITLE
[CATA][Transmog]

### ISSUE THREAD

**Issue by Supernachos12** [NRG-Wow/NRGWow-Bugtracker#84]
**Reporter(Player/Character) Name**: Supernacho

**Description**: After using the new transmog system, sometimes your item models just disappear.
and your char is almost, if not fully naked. Item lvl doesn't count in the character stats anymore even though you can still queue for dungeons. Relog fixes it.
https://imgur.com/a/0BfPJAF

**Current behaviour**: I have full T2 rogue transmogged, and sometimes after i teleport, i'm half or fully naked. 

**Expected behaviour**: Model of your items shouldn't disappear.

**Steps to reproduce the problem**:

1. Transmog all your gear
2. Teleport with portal or HS or whatever
3. Check your char.

**Comment by NRG-Wow** [comment]
Thanks for report we are investigating this

**Comment by Supernachos12** [comment]
Actually, even without transmog it happens.

So far i've noticed, when you tp somewhere and when you trade something it happens.
When you trade someone, the item you traded somehow ends up in a random slot of your toon.
Earlier i had all my gear slots filled with gems because i traded gems to someone.

**Comment by Illusie** [comment]
If I able to add to this issue without opening new one.
You also cannot save gears at Equipment Manager
All sets I done there are Red even the one I current wear.

**Comment by Wilcalaf** [comment]
Transmog issues have been solved abd the patch will be applied today.
@Illusie im not sure if the issue you are describing is related to the transmog.
