### ISSUE TITLE
[CATA][NPCs] Magistrix Eredania

### ISSUE THREAD

**Issue by Erocco** [NRG-Wow/NRGWow-Bugtracker#86]
**Description:** NPC Magistrix Eredania <Enchanting Trainer> is missing from zone Eversong Woods

**Current behaviour:** ---

**Expected behaviour:** NPC should be at coordinates should be 38.2, 78.6 in Eversong Woods

**Steps to reproduce the problem:** ---

**Comment by Wilcalaf** [comment]
Will be fixed on next restart. Thanks
