### ISSUE TITLE
[CATA][CORE] Naked glitch after sending mail

### ISSUE THREAD

**Issue by true-ede** [NRG-Wow/NRGWow-Bugtracker#92]
**Reporter(Player/Character) Name**: true-ede

**Description**: The worn gear glitches out after sending mail twice in a row without closing the mailbox. This only affects the appearance of my character. One or more piece of gear randomly disappears, but the item is there when I open up the character panel and I can get rid of the glitch by unequipping/equipping.

**Current behaviour**: Random gear piece(s) missing from appearance after sending mail for a second time in a row

**Expected behaviour**: None of the above

**Steps to reproduce the problem**:

1. Click on mailbox
2. Send something and don't close the mailbox
3. Send something again

**Comment by NRG-Wow** [comment]
This has been fixed after the transmog fix applied yesterday
