### ISSUE TITLE
Archaeology skill is +1 instead of +3

### ISSUE THREAD

**Issue by Ggilian** [NRG-Wow/NRGWow-Bugtracker#94]
[//]: # Archaeology

**Reporter(Player/Character) Name**:
Ggilian

**Description**: Describe the problem
All the professions give +3 skill, but Archaeology doesnt

**Current behaviour**: What happens
When i collect an artifact i get +1 skill

**Expected behaviour**: What should happen instead
When i collect an artifact i should get +3 skill ^^
**Steps to reproduce the problem**:

1. Change it into +3
2. 
3.

**Comment by NRG-Wow** [comment]
The Archeology dig is x1 and solving x3, this is intended so its not a bug.
