### ISSUE TITLE
[EN][Cata][Shaman] Hex

### ISSUE THREAD

**Issue by Illusie** [NRG-Wow/NRGWow-Bugtracker#95]
[//]: #  (Only reports in english will be allowed. and specific issues. everything like "ZOMG NOTHING WORKS" will be ignored / deleted)

**Reporter(Player/Character) Name**: ----

**Description**: Hex does not break from damage taken.

**Current behaviour**:  Right now when I get hex + under damage. I'm staying for atleast 4-5 sec or full duration of the hex. The hex should break from <?> of damage taken.

I saw some players use hex and still damage you while you hexed. It's not their fault it's server-sided fault. so I call you to check out the Hex / breaking cc.

Note that hex is not like polymorph / blind and other abilities that instantly break from damage.
Hex like Fear should break after <?> of time if taking damage. not every damage break it by the way. I'm not sure again about the amount of damage taken. ~

**Expected behaviour**: Hex should work like Fear (which work kinda good here but break too quick from damage taken) the hex is like the opposite, its not breaking from damage taken.

**Steps to reproduce the problem**:

1.  Get hex(aura) / cc
2. Take damage
3. Hex does not break for 80% up to 100% of the duration.

https://wow.gamepedia.com/Hex
https://wow.gamepedia.com/Crowd_control

reference:
http://www.arenajunkies.com/topic/147689-how-much-damage-breaks-hex/
I still have doubt about AJ but have fun reading it.

**Comment by NRG-Wow** [comment]
I just tested and i saw its breaking after some damage.
i will verify how much damage it is but it seem working ok

**Comment by Illusie** [comment]
@NRG-Wow great cause Im not PVP expert but when I'm hexed and taking massive damage from warrior+shaman and hex still remained I was like no way work that way I think the moment hex wore off or broke was when I died actually, that was bit fast for my eye to catch.

Thanks~

**Comment by MoireMoire** [comment]
Actually i got hexed couple times and it broke after 20-30k damage, seemed fine to me.

**Comment by Wilcalaf** [comment]
After checks Hex seems working as intended.
