### ISSUE TITLE
[CATA][NPC]Bile-O-Tron (Blackwind Descent RAID)

### ISSUE THREAD

**Issue by Boome01** [NRG-Wow/NRGWow-Bugtracker#97]
[//]: #  (Only reports in english will be allowed. and specific issues. everything like "ZOMG NOTHING WORKS" will be ignored / deleted)

[//]: # (Please write the titles of the issues following the format:)
[//]: # ([CATA][Quests][Zones] Quest name)
[//]: # ([WOTLK][Spells][Classes] Spell name)
[//]: # ([WOTLK][Talents][Classes] Talent name)
[//]: # ([CATA][Glyphs][Classes] Glyph name)
[//]: # ([CATA][NPCs] NPC name)

**Reporter(Player/Character) Name**: Boomy

**Description**: NPC that I mentioned in name of the topic is not working properly as it should to be able to deafeat boss smoothly without any bugs.

**Current behaviour**: NPC is after "Feud" "dead" and isn't "respawning" quick enough to protect players from instant dying from "Masacre" as it should do.

**Expected behaviour**: After "Feud" is finished NPC should "respawn" quick enough to protect players from taking that much damage from "Masacre".

**Steps to reproduce the problem**:

1. Bile-O-Tron needs to "respawn" quicker.

**Bonus comment**: I would like to ask for hight priority fix since this is content that is blocking all raiders from defeating Nefarian and basicly whole BWD content. Thank you for your cooperation :)

**Comment by NRG-Wow** [comment]
I have been trying to reproduce this for over 30 minutes and i was not able.
i spoke with some players involved to gather details and i have concluded that i have to come to see it next time you go because im not able to reproduce the issue.

**Comment by NRG-Wow** [comment]
Also if you can give any damage log to check from what exactly you died

**Comment by Boome01** [comment]
Sorry but I can't send screenshot. But we all died from Masacre spell that was casted right after Feud has finished. 
And we took incredible damage because Bile-O-Tron wasn't activated again after Feud

**Comment by MoireMoire** [comment]
I'm actually stupid because i didn't take a screenshot, but both times we got oneshotted by spells doing full damage, it was either 1 mln each with massacre or 200k from the spit (people were way above 10k hp).

**Comment by NRG-Wow** [comment]
Please contact a GM in game next time to you go there so he can watch and help us find whats the issue

The issue will be settled after we can see what is going on in live

**Comment by Illusie** [comment]
If they are not spreading they probably die from not staying in /x range from each other.
the best way is to stream then show video. I couldn't understand anything you said

**Comment by MoireMoire** [comment]
Avoid random comments Illusie, thx.

**Comment by MoireMoire** [comment]
Not being spread cause every person in the range to drop to 1. You clearly have no idea what you are talking about. Again avoid random comments.

**Comment by Illusie** [comment]
I know exactly what you talk about but it took me like 30min to figure out what the hell you talk about.
because the NPC is robot he doesn't "spawn" or "respawn" he just go offline.

here: https://www.youtube.com/watch?v=qj7ORcTBPow&t=85s
1:38 - Bile-O-Tron is back online.
1:43 - massacare.

hf~

**Comment by MoireMoire** [comment]
Editing every comment 10 times doesn't hide you toxicity dear troll. Linking me a youtube video of how the boss is supposed to work doesn't change the fact that bile-o-tron wasn't back online by the time massacre happened. Muricans by the way, join fresh where you belong.

**Comment by virpyre** [comment]
From what I have noticed is Bile-o-tron wanders around the room throughout the fight, It will apply Finkle's Mixture on the raid however throughout the fight Chimaeron will cast _Caustic Slime_ which will weaken Bile-o-tron. It will have a *System Failure* for a short period of time while it _Reroutes Power_ it will be inactive during this time. Chimaeron’s starts Feud rendering him unable to attack for ~30 seconds. While he is feuding it will kill any raid member instantly. Therefore, during Feud, the raid needs to stack on one another and use **ALL** healing possible to top each other off because you need to split the damage amongst everyone. He will end _Feud_ with a _Massacre_ at which time the Bile-o-tron will become active again.

[Normal Chimaeron Fight](https://www.youtube.com/watch?v=LjuB-nAAUfg)

**Comment by Boome01** [comment]
Yes, but sometimes Bile-O-Tron disables when he shouldn't be.

He should be disabled while Feud is active only.

**Comment by MoireMoire** [comment]
1st thing virpyre, feud doesn't kill instantly anybody, all it does is a massive aoe damage, that's why people stack. Second what we are saying is that by the time massacre is being cast bile-o-tron is not back active.

**Comment by virpyre** [comment]
A GM will need to be present than to see this in your raid party then because from testing I have not seen anything.

**Comment by MoireMoire** [comment]
I think a GM has been there this morning with our guild master. Anyways if that didn't happen we will go this afternoon to let him witness that.

**Comment by NRG-Wow** [comment]
Alright so after watching the fight, i couldnt see what was reported on this issue but i did see other bug that was killing them.
For some reason Feud is being interrupted the same moment it starts

**Comment by NRG-Wow** [comment]
After hours of testing i was able to reproduce the issue described on here, in the process both bugs were fixed.
Feud being interrupted randomly on normal (should be interrupted only on hc by nefarian after 2 seconds)
and also that rare issue that was causing the bot to not grant a buff even after he wakes up sometimes.

Both of em are fixed and will be applied next patch. Thanks for report!!
