### ISSUE TITLE
Warlock pet

### ISSUE THREAD

**Issue by MoireMoire** [NRG-Wow/NRGWow-Bugtracker#99]
[Issue]: # Warlock pet getting stuck
[Zone]: # Mostly in dungeons but everywhere, just way less (happens every time in Vortex Pinnacle last humanoid pack)

**Reporter(Player/Character) Name**: Moire

**Description**: In some zones pet just gets stuck, doesn't move but still can use spells. After i resummon if i'm near where he got stuck things will repeat

**Comment by NRG-Wow** [comment]
Whole pet system requires a rewrite.
Gonna see when we can push it.

**Comment by hguy23** [comment]
Will be fixed with new pathfinding patch.

**Comment by Wilcalaf** [comment]
Please retry after patch applied today

**Comment by hguy23** [comment]
@moiremoire

**Comment by MoireMoire** [comment]
Feels a lot better after rewriting, but sometimes when the ground is not plain he moves back and forth while attacking a mob

**Comment by hguy23** [comment]
Should be good now, 1 more fix comming.
